### ISSUE TITLE
Empty error message Installer

### ISSUE THREAD

**Issue by Ghoja** [SukramJ/hahomematic#103]
![image](https://user-images.githubusercontent.com/15338292/147564853-b0f0fc3e-8db2-4dbd-9dca-2237fa30f794.png)
getting these error by intial configuration the integration and was not able to continue. after i removed the callback URL / Port i was able to continue.

**Comment by SukramJ** [comment]
What did you enter for callback / port?
Please add the corresponding error log.

**Comment by Ghoja** [comment]
I used the ip address of my Synology NAS (with the homeassistent docker container) and the port 8123 (webinterface)

2021-12-28 12:56:05 ERROR (MainThread) [custom_components.hahm.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/hahm/config_flow.py", line 212, in async_step_interface
    await _async_validate_input(self.hass, self.data)
  File "/config/custom_components/hahm/config_flow.py", line 128, in _async_validate_input
    control_unit = ControlConfig(
  File "/config/custom_components/hahm/control_unit.py", line 435, in get_control_unit
    return ControlUnit(self)
  File "/config/custom_components/hahm/control_unit.py", line 89, in __init__
    self._central: CentralUnit = self.create_central()
  File "/config/custom_components/hahm/control_unit.py", line 358, in create_central
    xml_rpc_server = register_xml_rpc_server(
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_server.py", line 341, in register_xml_rpc_server
    xml_rpc = XmlRpcServer(local_ip, local_port)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_server.py", line 266, in __init__
    self._simple_xml_rpc_server = SimpleXMLRPCServer(
  File "/usr/local/lib/python3.9/xmlrpc/server.py", line 605, in __init__
    socketserver.TCPServer.__init__(self, addr, requestHandler, bind_and_activate)
  File "/usr/local/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address in use

**Comment by SukramJ** [comment]
I add the messing error message. Thanks for reporting.

Are you aware of the case when to set callback ip and port? 
Ip of your sync and ha port 8123 makes no sense.

**Comment by SukramJ** [comment]
Latest release contains a simple error message and restarts the config_flow on error.
