### ISSUE TITLE
Cover (HDM2) no longer working

### ISSUE THREAD

**Issue by zngguvnf** [SukramJ/hahomematic#1033]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After the last update of HomeAssistant and / or custom component (unfortunately both have been updated directly after each other) I can no longer raise / lower my HomeMatic blinds (HmIP-HDM2) via HomeAssistant. 

### What version of HomematicIP (local) has the issue?

1.34.1

### What type of installation are you running?

Home Assistant Supervised

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/homematicip_local/cover.py:178
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 21:25:24 (5 occurrences) 
Last logged: 21:33:44

[139885054673824] NoneTypeEntity.send_value() got an unexpected keyword argument 'collector'
[139885144763520] NoneTypeEntity.send_value() got an unexpected keyword argument 'collector'
[139885003359664] NoneTypeEntity.send_value() got an unexpected keyword argument 'collector'
[139885055113728] NoneTypeEntity.send_value() got an unexpected keyword argument 'collector'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/homematicip_local/cover.py", line 178, in async_close_cover
    await self._hm_entity.close()
  File "/usr/local/lib/python3.10/site-packages/hahomematic/decorators.py", line 126, in wrapper_collector
    return_value = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hahomematic/platforms/custom/cover.py", line 377, in close
    await self._set_level(
  File "/usr/local/lib/python3.10/site-packages/hahomematic/platforms/custom/cover.py", line 282, in _set_level
    await self._e_combined.send_value(value=combined_parameter, collector=collector)
TypeError: NoneTypeEntity.send_value() got an unexpected keyword argument 'collector'
```

**Comment by SukramJ** [comment]
Thanks for reporting
