### ISSUE TITLE
Climate error on setting temperature for thermostat group with HM-CC-RT-DN devices 

### ISSUE THREAD

**Issue by itn3rd77** [SukramJ/hahomematic#123]
**custom_component/hahomematic version (if applicable):**
0.11.1

**Home Assistant version (if applicable):**
2021.12.7

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): Raspi3
- OS (Original, RaspberryMatic, debmatic/...): RaspberryMatic
- Version: 3.61.7.20211218

**Problem-relevant configuration:**

Do you use tls? YES
Do you use callback? NO
Do you use username and password? YES
Which interfaces do you use? RF / IP

**Describe the bug**
If trying to change  temperature for climate device (thermostat group with HM-CC-RT-DN devices) the following error pops up.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hahm/climate.py:149
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 09:47:36 (1 occurrences)
Last logged: 09:47:36

[140165618694128] '<=' not supported between instances of 'str' and 'float'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 586, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/hahm/climate.py", line 149, in async_set_temperature
    await self._hm_entity.set_temperature(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/devices/climate.py", line 184, in set_temperature
    await self._e_setpoint.send_value(float(temperature))
  File "/usr/local/lib/python3.9/site-packages/hahomematic/platforms/number.py", line 43, in send_value
    if value is not None and self._min <= value <= self._max:
TypeError: '<=' not supported between instances of 'str' and 'float'

```

**To Reproduce**
Change temperature of climate device which is a thermostat group with HM-CC-RT-DN devices.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by SukramJ** [comment]
Hi,
what happens, if you control your HM-CC-RT-DN directly.

**Comment by itn3rd77** [comment]
Controlling HM-CC-RT-DN directly is working fine.

**Comment by SukramJ** [comment]
Please try latest version

**Comment by itn3rd77** [comment]
Perfect. Works like a charm!

**Comment by SukramJ** [comment]
Fine. Do  you use hm covers?

**Comment by itn3rd77** [comment]
Hi. Yes I have a mixed setup of HmIP-BROLL and "old" HM-LC-Bl1PBU-FM devices. Anything special I should test?

**Comment by SukramJ** [comment]
No. Up, down works?

**Comment by itn3rd77** [comment]
Yepp. No problems so far.

**Comment by SukramJ** [comment]
Danke.

**Comment by itn3rd77** [comment]
Nichts zu danken. Du bist der Held ;-)

**Comment by SukramJ** [comment]
Du hast doch eine HmIP-BROLL getestet. Und beim Öffnen und Schliessen gab es keine Probleme.
Kannst du das Problem aus #125 nachvollziehen?

**Comment by itn3rd77** [comment]
Seems the is another problem which I have not faced before...

I have an automation with an action like shown below:

![grafik](https://user-images.githubusercontent.com/2655169/148019140-0004d991-a563-4edd-9108-63fb7c8a7153.png)

This is the YAML:

![grafik](https://user-images.githubusercontent.com/2655169/148019386-656472ec-7553-44f0-96a5-e1c999243d17.png)

Which is actually this device:

![grafik](https://user-images.githubusercontent.com/2655169/148020142-13737f50-706d-4b7b-a6e8-e5386e1519c7.png)

When the automation is triggered nothing happens and the following error is shown in the log:

```
2022-01-04 07:12:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities climate.group_radiatorcontrol_homeoffice_int0000002
```

**Comment by emufan** [comment]
Da auch climate, erst mal hier rein. wenn komplett was anderes, sag Bescheid, dann mach ich einen neuen Eintrag auf und lösche hier:
```
Logger: homeassistant.components.climate
Source: custom_components/hahm/climate.py:140
Integration: Klima (documentation, issues)
First occurred: 08:41:27 (2 occurrences)
Last logged: 08:41:28

Error adding entities for domain climate with platform hahm
Error while setting up hahm platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 747, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/hahm/generic_entity.py", line 82, in async_added_to_hass
    await self._hm_entity.load_data()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 559, in load_data
    self.update_entity()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 84, in update_entity
    _callback(*args)
  File "/config/custom_components/hahm/generic_entity.py", line 90, in _async_device_changed
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 540, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 302, in state_attributes
    data[ATTR_PRESET_MODE] = self.preset_mode
  File "/config/custom_components/hahm/climate.py", line 140, in preset_mode
    return self._hm_entity.preset_mode
  File "/usr/local/lib/python3.9/site-packages/hahomematic/devices/climate.py", line 397, in preset_mode
    if self._current_profile_name
  File "/usr/local/lib/python3.9/site-packages/hahomematic/devices/climate.py", line 489, in _current_profile_name
    inv_profiles[int(self._e_active_profile.value)]
KeyError: 6
```

und dann

```
Logger: hahomematic.xml_rpc_server
Source: custom_components/hahm/climate.py:140
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 08:41:52 (3 occurrences)
Last logged: 08:41:52

RPCFunctions.event: Failed to call callback for: HMIP-HmIP-RF, 000C9D89A193E1:1, SET_POINT_TEMPERATURE
RPCFunctions.event: Failed to call callback for: HMIP-HmIP-RF, 000C9D89A193E1:1, ACTUAL_TEMPERATURE
RPCFunctions.event: Failed to call callback for: HMIP-HmIP-RF, 000C9D89A193E1:1, BOOST_MODE
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_server.py", line 69, in event
    callback(interface_id, channel_address, parameter, value)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 391, in event
    self.update_entity(self.unique_id)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 84, in update_entity
    _callback(*args)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 84, in update_entity
    _callback(*args)
  File "/config/custom_components/hahm/generic_entity.py", line 90, in _async_device_changed
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 540, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 302, in state_attributes
    data[ATTR_PRESET_MODE] = self.preset_mode
  File "/config/custom_components/hahm/climate.py", line 140, in preset_mode
    return self._hm_entity.preset_mode
  File "/usr/local/lib/python3.9/site-packages/hahomematic/devices/climate.py", line 397, in preset_mode
    if self._current_profile_name
  File "/usr/local/lib/python3.9/site-packages/hahomematic/devices/climate.py", line 489, in _current_profile_name
    inv_profiles[int(self._e_active_profile.value)]
KeyError: 6
```
Aufgetreten im Reboot nach Update auf .12

**Comment by SukramJ** [comment]
Bitte mach ein eigenes Issue auf.

**Comment by SukramJ** [comment]
Was passiert wenn du  eine Entität verwendest?
Schau die mal deine Geräte an. Hast Du da doppelte Einträge?
Bei meinem HmIP-BWTH habe ich keine Probleme.

**Comment by itn3rd77** [comment]
Hab die beiden Entitäten der Gruppe einzeln der Automatisierung hinzugefügt und dann geht es.

![grafik](https://user-images.githubusercontent.com/2655169/148058399-d84da821-bca3-4c15-b3bf-d485907ad394.png)

**Comment by SukramJ** [comment]
> Schau die mal deine Geräte an. Hast Du da doppelte Einträge?

Hast Du hier mal geschaut?

**Comment by itn3rd77** [comment]
> > Schau die mal deine Geräte an. Hast Du da doppelte Einträge?
> 
> Hast Du hier mal geschaut?


Sorry ganz vergessen. Nee nix doppeltes zu sehen.

**Comment by SukramJ** [comment]
Ist das noch eine Testinstallation, oder schon mehr?

**Comment by itn3rd77** [comment]
Ich nutze das produktiv und es greift auch nur eine Instanz auf die CCU zu, fallst Du das meinst.

**Comment by SukramJ** [comment]
Ich hätte sonst gesagt Integration löschen und neu anlegen. Aber ich hab da auch keinen konkreten Verdacht, warum es bei dir nicht funktioniert.

**Comment by itn3rd77** [comment]
Hi,

habe das Update auf die 0.13.0 gemacht. Jetzt klappt es auf jedenfall. Ob es an dem Fix: "Fix unique_id for heating_groups" liegt, kann ich nicht sagen. Jetzt klappt die Autmation auf jedenfall, wenn ich das Gerät mit climate.set_tempature auswähle.

Danke vielmals!
