### ISSUE TITLE
Unable to properly connect to Rasperrymatic

### ISSUE THREAD

**Issue by TheEnjinia** [SukramJ/hahomematic#1244]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Had some initial Problems with devices, like sensors not showing up. Decided to reinstall the HomematicIP (local) integration. Since then Devices are not showing up and looking into the log files, it seems there is a bigger connection problem present.

### What version of HomematicIP (local) has the issue?

1.45.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-1ca76c79e21bf96699a9b306397318f7.json.txt](https://github.com/danielperna84/hahomematic/files/12841535/config_entry-homematicip_local-1ca76c79e21bf96699a9b306397318f7.json.txt)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
2023-10-08 21:08:57.207 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-08 21:08:57.209 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hahm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-08 21:08:57.211 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-08 21:09:19.028 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp-remote @ 192.168.0.192: Error connecting to ('192.168.0.192', 6053): [Errno 113] Connect call failed ('192.168.0.192', 6053) (SocketAPIError)
2023-10-08 21:10:13.973 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:10:14.651 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:10:14.657 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2023-10-08 21:10:15.388 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:10:15.868 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp-remote1 @ 192.168.0.171: Error connecting to ('192.168.0.171', 6053):  (SocketAPIError)
2023-10-08 21:10:15.969 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:10:16.901 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration hahm: cannot import name 'AVAILABLE_HM_PLATFORMS' from 'hahomematic.const' (/usr/local/lib/python3.11/site-packages/hahomematic/const.py)
2023-10-08 21:10:16.901 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2067, in _load_integration
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 838, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 855, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/hahm/__init__.py", line 10, in <module>
    from .const import DOMAIN, HAHM_PLATFORMS
  File "/config/custom_components/hahm/const.py", line 6, in <module>
    from hahomematic.const import AVAILABLE_HM_PLATFORMS
ImportError: cannot import name 'AVAILABLE_HM_PLATFORMS' from 'hahomematic.const' (/usr/local/lib/python3.11/site-packages/hahomematic/const.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 96, in _async_start
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 183, in gather_with_concurrency
    return await gather(
           ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 181, in sem_task
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 872, in async_init
    flow, result = await task
                   ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 890, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 992, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2088, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2074, in _load_integration
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
2023-10-08 21:10:30.970 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2023-10-08 21:10:31.660 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:10:32.261 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:10:47.263 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2023-10-08 21:10:48.131 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:10:48.994 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:11:03.996 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2023-10-08 21:11:04.664 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:11:05.281 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:11:20.283 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2023-10-08 21:11:20.967 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:11:21.583 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:11:36.585 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2023-10-08 21:11:37.241 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:11:37.841 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:11:54.814 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:11:55.440 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:11:55.456 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2023-10-08 21:11:56.183 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:11:56.836 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:12:11.838 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2023-10-08 21:12:12.452 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:12:13.135 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:12:28.137 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2023-10-08 21:12:28.749 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [Unable to connect (2, 'No such file or directory').]
2023-10-08 21:12:29.397 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [Unable to connect (2, 'No such file or directory').]
```

**Comment by SukramJ** [comment]
You should start with cleanup your environment. You still have the old version of the integration (hahm) on your system. Remove it also from the custom components directory.

**Comment by SukramJ** [comment]
This is less a problem with integration than with your own environment.
I think you missed to read the [release notes](https://github.com/danielperna84/custom_homematic/releases/tag/1.0.0) in march **2022** when then integration was renamed from hahm to Homematic(IP) Local and users should work through a [migration plan](https://github.com/danielperna84/custom_homematic/wiki/Migration--from-domain-hahm-to-homematicip_local).
