### ISSUE TITLE
Cannot connect to CCU3

### ISSUE THREAD

**Issue by sebastiankruk** [SukramJ/hahomematic#1268]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I was able to use built-in homematic integration but as it was not updating the state of the thermostats I decided to switch to homematicip_local

When prompted for the configuration details I have provided the same information as before. 
However I was not prompted for local_port or network_mode.

Somehow only first part was recorded and I am presented with the same configuration screen again for callback ip and port, and jsonport. 

Does not seem to work.

Here is what I found in logs:

Error setting up entry ccu3-webui for homematicip_local

> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/homematicip_local/__init__.py", line 47, in async_setup_entry
>     control = await ControlConfig(
>               ^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/homematicip_local/control_unit.py", line 522, in create_control_unit
>     return ControlUnit(self)
>            ^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/homematicip_local/control_unit.py", line 205, in __init__
>     super().__init__(control_config=control_config)
>   File "/config/custom_components/homematicip_local/control_unit.py", line 112, in __init__
>     self._central: CentralUnit = self._create_central()
>                                  ^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/homematicip_local/control_unit.py", line 197, in _create_central
>     ).create_central()
>       ^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/hahomematic/central/__init__.py", line 1364, in create_central
>     return CentralUnit(self)
>            ^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/hahomematic/central/__init__.py", line 119, in __init__
>     self._xml_rpc_server.register_central(self)
>   File "/usr/local/lib/python3.11/site-packages/hahomematic/central/xml_rpc_server.py", line 210, in register_central
>     if not self._centrals.get(central.name):
>            ^^^^^^^^^^^^^^
> AttributeError: 'XmlRpcServer' object has no attribute '_centrals'

### What version of HomematicIP (local) has the issue?

1.47.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.67.10

### What hardware are you running for your system?

HA on Ubuntu/Docker

### Which config details do you use

- [X] Username and password
- [X] TLS
- [X] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[home-assistant_homematicip_local_2023-10-26T21-01-04.963Z.log](https://github.com/danielperna84/hahomematic/files/13182899/home-assistant_homematicip_local_2023-10-26T21-01-04.963Z.log)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
2023-10-26 22:44:16.161 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-26 22:44:36.871 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ccu3-webui for homematicip_local
File "/config/custom_components/homematicip_local/__init__.py", line 47, in async_setup_entry
File "/config/custom_components/homematicip_local/control_unit.py", line 522, in create_control_unit
File "/config/custom_components/homematicip_local/control_unit.py", line 205, in __init__
File "/config/custom_components/homematicip_local/control_unit.py", line 112, in __init__
File "/config/custom_components/homematicip_local/control_unit.py", line 197, in _create_central
2023-10-26 22:48:24.905 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ccu3-webui for homematicip_local
File "/config/custom_components/homematicip_local/__init__.py", line 47, in async_setup_entry
File "/config/custom_components/homematicip_local/control_unit.py", line 522, in create_control_unit
File "/config/custom_components/homematicip_local/control_unit.py", line 205, in __init__
File "/config/custom_components/homematicip_local/control_unit.py", line 112, in __init__
File "/config/custom_components/homematicip_local/control_unit.py", line 197, in _create_central
2023-10-26 22:51:16.787 DEBUG (MainThread) [custom_components.homematicip_local.config_flow] ConfigFlow.step_interface, no user input
2023-10-26 22:51:26.342 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ccu3-webui for homematicip_local
File "/config/custom_components/homematicip_local/__init__.py", line 47, in async_setup_entry
File "/config/custom_components/homematicip_local/control_unit.py", line 522, in create_control_unit
File "/config/custom_components/homematicip_local/control_unit.py", line 205, in __init__
File "/config/custom_components/homematicip_local/control_unit.py", line 112, in __init__
File "/config/custom_components/homematicip_local/control_unit.py", line 197, in _create_central
```

**Comment by SukramJ** [comment]
So when I look at your log you have a lot of other problems. what did you enter in the configuration?

**Comment by sebastiankruk** [comment]
![Screenshot_20231027-052617.jpg](https://github.com/danielperna84/hahomematic/assets/1426486/96a448a1-6aed-4cb8-ae5f-a62cae05c042)

Here are the only things I have changed.
I tried using h.kruk.me instead of 192.168.1.50 but with the same effect.

**Comment by SukramJ** [comment]
Why do you fill out the callback fields and json port?

**Comment by sebastiankruk** [comment]
> Why do you fill out the callback fields and json port?

I thought that when HA is on Docker that's the way it should be set up. The old integration did not seem to work without it. Let me try to skip it.

**Comment by sebastiankruk** [comment]
> > Why do you fill out the callback fields and json port?
> 
> I thought that when HA is on Docker that's the way it should be set up. The old integration did not seem to work without it. Let me try to skip it.

It did help. I'll play with it when I'm back home but this is big progress. Thank you.

**Comment by SukramJ** [comment]
Please read the docs.

**Comment by sebastiankruk** [comment]
Thanks for you help. At least I can see now integration running. 

I did read the docs. Misunderstood that part on json_port I guess - with TLS enabled I don't have to provided it. But I understood from reading https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port that when HA is on Docker I should provide callback_* to make sure HM will have a way to come back to this integration. 

Without either of those setup - I can see my devices alright ... but changing anything (like the target mode or temperature on HmIP-eTRV2 is not reflected on the UI until I reload the integration. Had the same issue with the built in integration. My understanding was that the back channel from HM to HA cannot be established. 

8123 is the port at which HA can be found from outside the box Docker is installed. Should there be some other port set for XML-RPC instead?

**Comment by danielperna84** [comment]
> 8123 is the port at which HA can be found from outside the box Docker is installed. Should there be some other port set for XML-RPC instead?

Yes. 8123 is already blocked by Home Assistant. You have to select a port that is not in use by the system.

**Comment by sebastiankruk** [comment]
> > 8123 is the port at which HA can be found from outside the box Docker is installed. Should there be some other port set for XML-RPC instead?
> 
> Yes. 8123 is already blocked by Home Assistant. You have to select a port that is not in use by the system.

That explains it all. Thank you. It works now :)
