### ISSUE TITLE
Climate errors

### ISSUE THREAD

**Issue by emufan** [SukramJ/hahomematic#129]
Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
0.12.0

**Home Assistant version (if applicable):**
2021.12.7

**CCU version:**
- CCU3
- OS Original 
- Version 3.61.7

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? IP

Bekomme auch viele climate.py Fehler

```
Logger: homeassistant.components.climate
Source: custom_components/hahm/climate.py:140
Integration: Klima (documentation, issues)
First occurred: 08:41:27 (2 occurrences)
Last logged: 08:41:28

Error adding entities for domain climate with platform hahm
Error while setting up hahm platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 747, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/hahm/generic_entity.py", line 82, in async_added_to_hass
    await self._hm_entity.load_data()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 559, in load_data
    self.update_entity()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 84, in update_entity
    _callback(*args)
  File "/config/custom_components/hahm/generic_entity.py", line 90, in _async_device_changed
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 540, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 302, in state_attributes
    data[ATTR_PRESET_MODE] = self.preset_mode
  File "/config/custom_components/hahm/climate.py", line 140, in preset_mode
    return self._hm_entity.preset_mode
  File "/usr/local/lib/python3.9/site-packages/hahomematic/devices/climate.py", line 397, in preset_mode
    if self._current_profile_name
  File "/usr/local/lib/python3.9/site-packages/hahomematic/devices/climate.py", line 489, in _current_profile_name
    inv_profiles[int(self._e_active_profile.value)]
KeyError: 6
```

und dann

```
Logger: hahomematic.xml_rpc_server
Source: custom_components/hahm/climate.py:140
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 08:41:52 (3 occurrences)
Last logged: 08:41:52

RPCFunctions.event: Failed to call callback for: HMIP-HmIP-RF, aaa:1, SET_POINT_TEMPERATURE
RPCFunctions.event: Failed to call callback for: HMIP-HmIP-RF, aaa:1, ACTUAL_TEMPERATURE
RPCFunctions.event: Failed to call callback for: HMIP-HmIP-RF, aaa:1, BOOST_MODE
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_server.py", line 69, in event
    callback(interface_id, channel_address, parameter, value)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 391, in event
    self.update_entity(self.unique_id)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 84, in update_entity
    _callback(*args)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 84, in update_entity
    _callback(*args)
  File "/config/custom_components/hahm/generic_entity.py", line 90, in _async_device_changed
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 540, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 302, in state_attributes
    data[ATTR_PRESET_MODE] = self.preset_mode
  File "/config/custom_components/hahm/climate.py", line 140, in preset_mode
    return self._hm_entity.preset_mode
  File "/usr/local/lib/python3.9/site-packages/hahomematic/devices/climate.py", line 397, in preset_mode
    if self._current_profile_name
  File "/usr/local/lib/python3.9/site-packages/hahomematic/devices/climate.py", line 489, in _current_profile_name
    inv_profiles[int(self._e_active_profile.value)]
KeyError: 6
```
Aufgetreten im Reboot nach Update auf .12

Gibt auch noch 206 mehr dazu

```
Logger: hahomematic.xml_rpc_server
Source: custom_components/hahm/climate.py:140
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 09:56:52 (206 occurrences)
Last logged: 12:20:45

RPCFunctions.event: Failed to call callback for: HMIP-HmIP-RF, aaa:1, SET_POINT_TEMPERATURE
RPCFunctions.event: Failed to call callback for: HMIP-HmIP-RF, aaa:1, ACTUAL_TEMPERATURE
RPCFunctions.event: Failed to call callback for: HMIP-HmIP-RF, bbb:1, SET_POINT_TEMPERATURE
RPCFunctions.event: Failed to call callback for: HMIP-HmIP-RF, bbb:1, HUMIDITY
RPCFunctions.event: Failed to call callback for: HMIP-HmIP-RF, bbb:1, ACTUAL_TEMPERATURE
```

aaa und bbb = HmIP-BWTH

**Comment by SukramJ** [comment]
Schau die mal bitte dein gerät in der CCU an:
Welches Profil ist aktiv?

**Comment by SukramJ** [comment]
Ich denke das du Profil 6 eingestellt hast.
Bisher war ich davon ausgegangen, das nur 1-3 beim BWTH als Heizprofile nutzbar. 4-6 waren für den Kühlmodus.
Ich hab dazu aber keine CCU Doku gefunden, die das untermauert.

Ich hab das aber in der letzten Version geändert, so das jetzt 1-6 beim BWTH nutzbar sind.
In Klimagruppen sind aber nur 1-3 nutzbar.
Also teste bitte mal die letzte Version.

**Comment by emufan** [comment]
Ja, ich nutze überall 6 beim BWTH. Habe auch nirgendwo eine Einschränung oder Meldung bekommen, dass ich das nicht nutzen soll. Und funktioniert auch (ohne HA und mit der alten HM-Integration).

Bei den Heizgruppe aus HmIP-WTH-2 und HmIP-eTRV-C-2 die 3, da die HmIP-eTRV-C-2 nur 3 haben. In der Heizgruppe könnte ich aber schon 6 einstellen, nur wird das dann nicht direktvernüpft abgeglichen mit dem HmIP-eTRV-C-2, weil es dort nur die besagten 3 gibt. mE ein Konzeptfehler bei EQ3.

**Comment by SukramJ** [comment]
kann das Ticket geschlossen werden?

**Comment by emufan** [comment]
Yup. Keine Fehlermeldungen mehr! Danke! 👍
