### ISSUE TITLE
XMLStreamException: Unknown type: data

### ISSUE THREAD

**Issue by Caleb1424** [SukramJ/hahomematic#1303]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Since I upgrade from [pyhomematic](https://github.com/danielperna84/pyhomematic) to HomematicIP (local) I got exeptions in the ccu3 log. Also since this update the ccu3 is not as stable as before. Maybe the rasperrymatic Update to 3.71.12.20231020 could be responsible for that. I have to reboot the ccu3 once per week. While I was looking for the reason for that I saw the exceptions.
Besides this instabilities and logged exceptions, HA with the integration works and shows all values. The ping/pong is working. The CCU3 can reach the ha server.

### What version of HomematicIP (local) has the issue?

1.49.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.71.12.20231020

### What hardware are you running for your system?

HA as VM under Synology NAS.

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[home-assistant_homematicip_local_2023-11-28T19-12-55.627Z_shorten.log](https://github.com/danielperna84/hahomematic/files/13492616/home-assistant_homematicip_local_2023-11-28T19-12-55.627Z_shorten.log)
[ccu3-webui-2023-11-28 (1).log](https://github.com/danielperna84/hahomematic/files/13492691/ccu3-webui-2023-11-28.1.log)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
2023-11-28 20:56:59,309 de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler TRACE [ccu3-HmIP-RF_WorkerPool-1] Could not parse response data from interface: ccu3-HmIP-RF 
de.eq3.cbcs.legacy.communication.rpc.RpcSerializationException: javax.xml.stream.XMLStreamException: Unknown type: data
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:175) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
	at com.sun.proxy.$Proxy39.multicall(Unknown Source) ~[?:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.multicall(LegacyBackendClient.java:234) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleReceivedStatusData(LegacyBackendNotificationHandler.java:273) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleBackendNotification(LegacyBackendNotificationHandler.java:162) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:106) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:39) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_382]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_382]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_382]
```

### Additional information

When I deactivate the HomematicIP (local) Intergration, the above error with this stacktrace is gone. After activating the integration again, a few seconds later it comes back and stays.
My investigations: The ccu3 send an system.multicall and cannot parse the response comming from ha.
These multicalls comes every few seconds for my two HAPs working as LAN Gateways.
It is a big installation with over 94 devices. HmIP and HmIPW. I have one DRAP. The HUB ist called "ccu3".

**Comment by SukramJ** [comment]
Thanks for reporting this.
I am using RaspberryMatic 3.71.12.20231020 and i cannot reproduce this on my systems.

Looks like this is related to the HmIP-Server (ccu3-HmIP-RF).
Now it would of course be interesting to know why the HmIPServer has a problem with the data element (`Unknown type: data`).
I'm also surprised at the very high frequency of errors.

Basically, I don't think the problem lies in the integration, even if it might trigger these messages on your system. 
Of course, we also use a standard framework for XML-RPC communication, so we don't put together any messages ourselves.
So it would be good if you could post this error in the Homematic forum so that the Homematic experts can take a look at it.

**Comment by Baxxy13** [comment]
Man sieht diese Meldungen nur wenn das Logging für "Homematic IP" auf TRACE steht. (Veränderungen am Loglevel benötigen einen Zentralenneustart)

TRACE benutzt man nur zum Debugging/Fehleranalyse, ich z.B. gucke mir TRACE-Logs an wenn jemand "IP-Anlernprobleme" hat.

Im "Normalbetrieb" ist ein TRACE-Logging definitiv zu viel des Guten.

Das Zeug wird auch im Forum keiner analysieren können/wollen. Kommt ja direkt aus dem Closed-Source HmIP-Server.
Mann kann natürlich reingucken, man müsste aber schon JAVA-Experte sein um da was zu analysieren.
Letztlich müsste das eQ-3 analysieren, aber da man auf einer CCU3 nicht mal mit UI-Mitteln an ein TRACE-Log kommt wird das eher nix. 

Ich habe die Meldungen (auf dem Testsystem mit aktivem TRACE-Log) auch, funktionelle Einschränkungen oder Fehler kann ich aber nicht erkennen,

Meine Empfehlung:
HmIP - Loglevel auf ein normales Maß runterschrauben (INFO).

**Comment by SukramJ** [comment]
> HmIP - Loglevel auf ein normales Maß runterschrauben (INFO).

Hört sich sinnvoll an. TRACE hatte ich übersehen.

@Caleb1424 Ich würde das Ticket hier schliessen.
