### ISSUE TITLE
Integration does not start with 2024.1.0b0

### ISSUE THREAD

**Issue by ChristophCaina** [SukramJ/hahomematic#1340]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

HomematicIP_local does not start with the current Beta HA 2024.1.0b0

The system is showing the following warning in the notification area:
![image](https://github.com/danielperna84/hahomematic/assets/26391061/35f55c50-6b69-44cf-b03e-cc1aa0ac7546)

The following errors are logged:

```
Logger: homeassistant.config_entries
Source: config_entries.py:2087
First occurred: 11:57:29 (1 occurrences)
Last logged: 11:57:29

Error occurred loading flow for integration homematicip_local: Exception importing custom_components.homematicip_local.config_flow
```

```
Logger: homeassistant.loader
Source: loader.py:842
First occurred: 11:57:29 (1 occurrences)
Last logged: 11:57:29

Unexpected exception importing platform custom_components.homematicip_local.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/__init__.py", line 21, in <module>
    from .control_unit import ControlConfig, get_storage_folder
  File "/config/custom_components/homematicip_local/control_unit.py", line 87, in <module>
    from .support import (
  File "/config/custom_components/homematicip_local/support.py", line 128, in <module>
    class HmBinarySensorEntityDescription(HmEntityDescription, BinarySensorEntityDescription):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

```
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 11:56:42 (1 occurrences)
Last logged: 11:56:42

Setup failed for custom integration 'homematicip_local': Unable to import component: Exception importing custom_components.homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/__init__.py", line 21, in <module>
    from .control_unit import ControlConfig, get_storage_folder
  File "/config/custom_components/homematicip_local/control_unit.py", line 87, in <module>
    from .support import (
  File "/config/custom_components/homematicip_local/support.py", line 128, in <module>
    class HmBinarySensorEntityDescription(HmEntityDescription, BinarySensorEntityDescription):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 830, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.homematicip_local
```

```
Logger: homeassistant.loader
Source: loader.py:822
First occurred: 11:56:42 (1 occurrences)
Last logged: 11:56:42

Unexpected exception importing component custom_components.homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/__init__.py", line 21, in <module>
    from .control_unit import ControlConfig, get_storage_folder
  File "/config/custom_components/homematicip_local/control_unit.py", line 87, in <module>
    from .support import (
  File "/config/custom_components/homematicip_local/support.py", line 128, in <module>
    class HmBinarySensorEntityDescription(HmEntityDescription, BinarySensorEntityDescription):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

### What version of HomematicIP (local) has the issue?

1.51.0

### What was the last working version of HomematicIP (local)?

1.51.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9.20231130

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Additional information

worked well with the 2023.12. HA release, so probably some dependencies are changing with the upcomming HA version

**Comment by SukramJ** [comment]
Short hint:

> I am running the latest version of the custom_component (and Home Assistant)

**Comment by ChristophCaina** [comment]
thanks :)
HACS did not show that an update for HomematicIP_Local was available - even after getting the version information again.
