### ISSUE TITLE
CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF

### ISSUE THREAD

**Issue by J-89436** [SukramJ/hahomematic#1380]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Thermostats are no longer available in the Home Assistant overview and in the RaspberryMatic.
![Thermostat-Error](https://github.com/danielperna84/hahomematic/assets/62260727/9e97095e-89c4-47b0-9754-6bb865a724f5)

### What version of HomematicIP (local) has the issue?

1.33.0

### What was the last working version of HomematicIP (local)?

1.52.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9.20231130

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.1.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.1.63-haos-raspi",
    "supervisor": "2023.12.0",
    "host_os": "Home Assistant OS 11.4",
    "docker_version": "24.0.7",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "alphaess": {
      "version": "0.4.7",
      "requirements": [
        "alphaessopenapi==0.0.6"
      ]
    },
    "homematicip_local": {
      "version": "1.53.0",
      "requirements": [
        "hahomematic==2024.1.5"
      ]
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "homekit": {},
    "integration_type": "hub",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "loggers": [
      "hahomematic"
    ],
    "requirements": [
      "hahomematic==2024.1.5"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "version": "1.53.0",
    "zeroconf": [],
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "f3487de13fd1038b07de9939f94a7d7c",
      "version": 2,
      "minor_version": 1,
      "domain": "homematicip_local",
      "title": "RaspberryMatic",
      "data": {
        "instance_name": "RaspberryMatic",
        "host": "de838cd8-raspberrymatic",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          },
          "BidCos-RF": {
            "port": 2001
          },
          "VirtualDevices": {
            "port": 9292,
            "path": "/groups"
          }
        },
        "enable_system_notifications": true
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "1D89B554CC",
      "disabled_by": null
    },
    "platform_stats": {},
    "devices": [],
    "system_information": {
      "available_interfaces": [
        "VirtualDevices"
      ],
      "auth_enabled": true,
      "https_redirect_enabled": false,
      "serial": "**REDACTED**"
    }
  }
}

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: Raspberry Pi 4 Model B Rev 1.1 (oci), OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Running seedrng: OK
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.5, OK
Identifying Homematic RF-Hardware: HmRF: n/a, HmIP: n/a, OK
Updating Homematic RF-Hardware: no GPIO/USB connected RF-hardware found
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: not required
Starting rfd: no BidCos-RF hardware found
Starting HMIPServer: .........OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.73.9.20231130 (raspmatic_oci_arm64)
```

### Additional information

Home Assistant Core
CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
18:24:42 – (WARNUNG) runner.py - Die Nachricht ist zum ersten Mal am 17:18:28 aufgetreten und erscheint 768 mal
Subscription to 192.168.69.39 failed, attempting to poll directly
17:19:26 – (WARNUNG) Sonos
No configuration for request_sync available
17:19:14 – (FEHLER) Google Assistant
Waiting on integrations to complete setup: synology_dsm
17:19:10 – (WARNUNG) bootstrap.py
ENERGY_KILO_WATT_HOUR was used from alphaess, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/CharlesGillanders/homeassistant-alphaESS/issues
17:18:31 – (WARNUNG) helpers/deprecation.py - Die Nachricht ist zum ersten Mal am 17:18:31 aufgetreten und erscheint 2 mal
CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [()]
17:18:28 – (WARNUNG) Homematic(IP) Local (benutzerdefinierte Integration) - Die Nachricht ist zum ersten Mal am 17:18:27 aufgetreten und erscheint 2 mal
Error while setting up mobile_app platform for sensor
17:18:27 – (FEHLER) Sensor
Error adding entities for domain sensor with platform mobile_app
17:18:27 – (FEHLER) Sensor
Host 192.168.69.58:443, could not verify a working RTSP url
17:18:26 – (FEHLER) components/reolink/host.py - Die Nachricht ist zum ersten Mal am 17:18:26 aufgetreten und erscheint 2 mal
Using slower stringprep, consider compiling the faster cython/libidn one.
17:18:22 – (WARNUNG) components/harmony/data.py
Home Assistant Core
2024-01-11 17:17:54.740 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-11 17:17:54.744 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration alphaess which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-11 17:17:54.747 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-11 17:18:22.578 WARNING (MainThread) [slixmpp.stringprep] Using slower stringprep, consider compiling the faster cython/libidn one.
2024-01-11 17:18:26.193 ERROR (MainThread) [reolink_aio.api] Host 192.168.69.58:443, could not verify a working RTSP url
2024-01-11 17:18:26.422 ERROR (MainThread) [reolink_aio.api] Host 192.168.69.58:443, could not verify a working RTSP url
2024-01-11 17:18:27.168 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [()]
2024-01-11 17:18:27.645 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform mobile_app
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 639, in state
numerical_value = int(value)
^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Charging'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 642, in state
numerical_value = float(value)
^^^^^^^^^^^^
ValueError: could not convert string to float: 'Charging'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1278, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in __async_calculate_state
state = self._stringify_state(available)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 947, in _stringify_state
if (state := self.state) is None:
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 646, in state
raise ValueError(
ValueError: Sensor sensor.carolas_iphone_battery_state has device class 'battery', state class 'None' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Charging' (<class 'str'>)
2024-01-11 17:18:27.673 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mobile_app platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 639, in state
numerical_value = int(value)
^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Charging'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 642, in state
numerical_value = float(value)
^^^^^^^^^^^^
ValueError: could not convert string to float: 'Charging'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1278, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in __async_calculate_state
state = self._stringify_state(available)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 947, in _stringify_state
if (state := self.state) is None:
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 646, in state
raise ValueError(
ValueError: Sensor sensor.carolas_iphone_battery_state has device class 'battery', state class 'None' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Charging' (<class 'str'>)
2024-01-11 17:18:28.687 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [()]
2024-01-11 17:18:28.694 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2024-01-11 17:18:28.728 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [()]
2024-01-11 17:18:29.243 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [()]
2024-01-11 17:18:31.038 WARNING (MainThread) [homeassistant.const] ENERGY_KILO_WATT_HOUR was used from alphaess, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/CharlesGillanders/homeassistant-alphaESS/issues
2024-01-11 17:18:31.048 WARNING (MainThread) [homeassistant.const] POWER_WATT was used from alphaess, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please create a bug report at https://github.com/CharlesGillanders/homeassistant-alphaESS/issues
2024-01-11 17:18:44.245 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2024-01-11 17:18:44.281 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [()]
2024-01-11 17:18:44.795 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [()]
2024-01-11 17:18:59.797 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2024-01-11 17:18:59.831 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [()]
2024-01-11 17:19:00.329 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [()]
2024-01-11 17:19:10.486 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: synology_dsm
2024-01-11 17:19:14.307 ERROR (MainThread) [homeassistant.components.google_assistant.http] No configuration for request_sync available
2024-01-11 17:19:15.361 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2024-01-11 17:19:15.594 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [()]
2024-01-11 17:19:26.617 WARNING (MainThread) [homeassistant.components.sonos] Subscription to 192.168.69.39 failed, attempting to poll directly
2024-01-11 17:19:28.602 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [()]
2024-01-11 17:19:43.604 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2024-01-11 17:19:43.634 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [()]
2024-01-11 17:19:44.195 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [()]
2024-01-11 17:19:59.196 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2024-01-11 17:19:59.228 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [()]
2024-01-11 17:19:59.841 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [()]
2024-01-11 17:20:14.843 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2024-01-11 17:20:14.877 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [()]
2024-01-11 17:20:15.398 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [()]
2024-01-11 17:20:30.400 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
2024-01-11 17:20:30.436 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [()]
2024-01-11 17:20:30.949 WARNING (MainThread) [hahomematic.central] CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [()]
2024-01-11 17:20:45.950 WARNING (MainThread) [hahomematic.central] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server Ra

------------------------------------------------------------------------------------

Interface RaspberryMatic-HmIP-RF nicht erreichbar.
Keine Verbindung zu Schnittstelle RaspberryMatic-HmIP-RF.

Diese Integration versucht eine automatische Wiederverbindung.

Weitere Informationen finden Sie in den Protokolldateien von Home Assistant.

Warnung - 11.1.2024

--------------------------------------------------------------------------------

Logger: hahomematic.central
Source: custom_components/homematicip_local/control_unit.py:123
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 17:18:27 (2 occurrences)
Last logged: 17:18:28

CREATE_CLIENTS failed: No connection to interface RaspberryMatic-HmIP-RF [()]
CREATE_CLIENTS failed: No connection to interface RaspberryMatic-BidCos-RF [()]

Core
2024.1.2
Supervisor
2023.12.0
Operating System
11.4
Frontend
20240104.0

**Comment by SukramJ** [comment]
Was soll ich sagen. Die Integration kann keine Verbindung zu RaspberryMatic herstellen.
Da sind sehr viele Fehler im Log so das man den Wald vor lauter Bäumen nicht sehen kann. Bitte das nächste mal das Log als Datei anhängen.
Was hast du den bisher unternommen, um das Problem zu beseitigen. Neustarts sind immer hilfreich.

**Comment by danielperna84** [comment]
> ...and in the RaspberryMatic.

Die Formulierung klingt, als würde auch RaspberryMatic nicht funktionieren. Dann kann die Integration auch nicht funktionieren, und die eigentliche Quelle des Problems ist bei RaspberryMatic zu suchen.

**Comment by J-89436** [comment]
Ich habe den Home-Office Assistent mehrfach neu gestartet und auch sch komplett stromlos gemacht. Hat aber bis jetzt nichts geholfen.

**Comment by J-89436** [comment]
Jetzt scheint es erstmal wieder zu funktionieren. Nach dem ich den Home Assistant komplett über längere Zeit stromlos gemacht habe und nach dem Neustart die Thermostate über RaspberryMatic manuell wieder aktiviert habe. Ich hoffe das ich das nicht jedes Mal jetzt tun muss.
