### ISSUE TITLE
HomematicIP (local) cannot be downloaded after Update HA Core to 2024.2.1 

### ISSUE THREAD

**Issue by RueKow** [SukramJ/hahomematic#1435]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I used 1.54.0 with HA Core 2024.1.x successfully. After updating Core to 2024.2.1 the HomematicIP integration didn't work anymore. I have tried to reload the integration, unfortunately without success. Then I tried to reload custom_homematic from the HACS, but that didn't work either (see excerpt from the HA log).

### What version of HomematicIP (local) has the issue?

1.55.0

### What was the last working version of HomematicIP (local)?

1.54.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.73.9

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
2024-02-14 07:00:02.905 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139827476998080] Error handling message: Unknown error (unknown_error) Rüdiger from 192.168.178.68 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 899, in async_install
    await self.async_install_repository()
  File "/config/custom_components/hacs/repositories/base.py", line 982, in async_install_repository
    await self.download_content()
  File "/config/custom_components/hacs/repositories/base.py", line 629, in download_content
    await self.download_repository_zip()
  File "/config/custom_components/hacs/repositories/base.py", line 686, in download_repository_zip
    zip_file.extractall(self.content.path.local, extractable)
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1721, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1762, in _extract_member
    raise ValueError("Empty filename.")
ValueError: Empty filename.
```

**Comment by SukramJ** [comment]
Sorry, but this is not a problem of the integration. 
Check outstanding updates. Maybe HACS is outdated.

**Comment by Eckart0** [comment]
Same problem. But HACS is udated. 
HA Core == 2024.2.2
homematicip_local == 1.55.0

Log:
`Logger: homeassistant.setup
Source: setup.py:251
First occurred: 21:56:18 (1 occurrences)
Last logged: 21:56:18

Setup failed for custom integration 'homematicip_local': Unable to import component: Exception importing custom_components.homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/__init__.py", line 21, in <module>
    from .control_unit import ControlConfig, get_storage_folder
  File "/config/custom_components/homematicip_local/control_unit.py", line 87, in <module>
    from .support import (
  File "/config/custom_components/homematicip_local/support.py", line 128, in <module>
    class HmBinarySensorEntityDescription(HmEntityDescription, BinarySensorEntityDescription):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 835, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.homematicip_local`

Regards, Eckart

**Comment by SukramJ** [comment]
Definitely not the same, or do I miss the the same exception?
Looks like the integration is not updated to 1.55.

**Comment by SukramJ** [comment]
If the problem still exists after the update, the create your own issue and provide as much of the requested information, esp. the integration diagnostics is required.
