### ISSUE TITLE
Fehler beim Einrichten

### ISSUE THREAD

**Issue by Goifal** [SukramJ/hahomematic#1575]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Servus, 

es steht immer bei der Integration "Fehler beim Einrichten".  Ich kann zwar z.B. Lichter einschalten aber nicht mehr ausschalten. Statusupdates von Lichtern, Türkontakten usw. werden auch nicht aktualisiert. 

Habe die Ports auf der RaspberryMatic geöffnet -> keine Änderung
Habe alle Ports auf der RaspberryMatic aufgemacht und auch Vollzugriff -> keine Änderung
Neuen Benutzer mit Adminrechten angelegt -> keine Änderung
RaspberryMatic neu gestartet -> keine Änderung 
Homematic(IP) Local gelöscht und neu installiert -> keine Änderung
Home Assistant heruntergefahren und neu gestartet -> keine Änderung

### What version of HomematicIP (local) has the issue?

1.62.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.75.7.20240420

### What hardware are you running for your system?

Raspberrymatic: Pi3 / Home Assistant: Intel Nuc 

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
2024-05-30 17:01:25.847 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Homematic for homematicip_local
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 584, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/homematicip_local/__init__.py", line 56, in async_setup_entry
await control.start_central()
File "/config/custom_components/homematicip_local/control_unit.py", line 226, in start_central
await super().start_central()
File "/config/custom_components/homematicip_local/control_unit.py", line 126, in start_central
await self._central.start()
File "/usr/local/lib/python3.12/site-packages/hahomematic/central/__init__.py", line 313, in start
await self._start_clients()
File "/usr/local/lib/python3.12/site-packages/hahomematic/central/__init__.py", line 405, in _start_clients
await self._init_hub()
File "/usr/local/lib/python3.12/site-packages/hahomematic/central/__init__.py", line 489, in _init_hub
await self._hub.fetch_sysvar_data()
File "/usr/local/lib/python3.12/site-packages/hahomematic/platforms/hub/__init__.py", line 50, in fetch_sysvar_data
await self._update_sysvar_entities(include_internal=include_internal)
File "/usr/local/lib/python3.12/site-packages/hahomematic/platforms/hub/__init__.py", line 124, in _update_sysvar_entities
entity.write_value(value)
File "/usr/local/lib/python3.12/site-packages/hahomematic/platforms/hub/entity.py", line 123, in write_value
value = parse_sys_var(data_type=self.data_type, raw_value=value)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/hahomematic/support.py", line 112, in parse_sys_var
return to_bool(raw_value)
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/hahomematic/support.py", line 126, in to_bool
raise TypeError("invalid literal for boolean. Not a string.")
TypeError: invalid literal for boolean. Not a string.
2024-05-30 17:01:53.100 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-05-30 17:01:55.856 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/homematicip_local/control_unit.py", line 713, in _fetch_data
await self._central.fetch_sysvar_data()
File "/usr/local/lib/python3.12/site-packages/hahomematic/central/__init__.py", line 942, in fetch_sysvar_data
await self._hub.fetch_sysvar_data(include_internal=include_internal)
File "/usr/local/lib/python3.12/site-packages/hahomematic/platforms/hub/__init__.py", line 50, in fetch_sysvar_data
await self._update_sysvar_entities(include_internal=include_internal)
File "/usr/local/lib/python3.12/site-packages/hahomematic/platforms/hub/__init__.py", line 124, in _update_sysvar_entities
entity.write_value(value)
File "/usr/local/lib/python3.12/site-packages/hahomematic/platforms/hub/entity.py", line 123, in write_value
value = parse_sys_var(data_type=self.data_type, raw_value=value)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/hahomematic/support.py", line 112, in parse_sys_var
return to_bool(raw_value)
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/hahomematic/support.py", line 126, in to_bool
raise TypeError("invalid literal for boolean. Not a string.")
TypeError: invalid literal for boolean. Not a string.
```

**Comment by SukramJ** [comment]
Überprüf bitte mal deine Alarm / Logikwert Systemvariablen in einer steht ein Wert der weder `bool` noch `string` ist.

**Comment by Goifal** [comment]
Habe es gefunden jetzt funktioniert alles danke
