### ISSUE TITLE
no connection since updating rasperrymaric

### ISSUE THREAD

**Issue by bcf84** [SukramJ/hahomematic#1588]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After the Update of Raspberrymatic to 3.75.7.20240601 is no connection from Homeassistant to homematic. 
The UI of homematic works as expected. 
I've checked the firewall settings within the UI and nothing has changed, everything is open. 

### What version of HomematicIP (local) has the issue?

1.62.0

### What was the last working version of HomematicIP (local)?

1.62.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.75.7.20240601

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
Logger: homeassistant.config_entries
Quelle: config_entries.py:584
Erstmals aufgetreten: 07:21:06 (1 Vorkommnisse)
Zuletzt protokolliert: 07:21:06

Error setting up entry CCU2 for homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 584, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homematicip_local/__init__.py", line 56, in async_setup_entry
    await control.start_central()
  File "/config/custom_components/homematicip_local/control_unit.py", line 226, in start_central
    await super().start_central()
  File "/config/custom_components/homematicip_local/control_unit.py", line 126, in start_central
    await self._central.start()
  File "/usr/local/lib/python3.12/site-packages/hahomematic/central/__init__.py", line 313, in start
    await self._start_clients()
  File "/usr/local/lib/python3.12/site-packages/hahomematic/central/__init__.py", line 402, in _start_clients
    if await self._create_clients():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hahomematic/central/__init__.py", line 435, in _create_clients
    if client := await hmcl.create_client(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hahomematic/client/__init__.py", line 1122, in create_client
    return await _ClientConfig(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hahomematic/client/__init__.py", line 1024, in get_client
    check_proxy = await self._get_simple_xml_rpc_proxy()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hahomematic/client/__init__.py", line 1085, in _get_simple_xml_rpc_proxy
    await xml_proxy.do_init()
  File "/usr/local/lib/python3.12/site-packages/hahomematic/client/xml_rpc.py", line 98, in do_init
    if supported_methods := await self.system.listMethods():
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hahomematic/client/xml_rpc.py", line 126, in __async_request
    result = await self._looper.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Global task timeout
```

### Additional information

As of yesterday, before updating raspberrymatic, everything worked fine.

**Comment by SukramJ** [comment]
Restart raspberrymatic, then restart HA?

**Comment by SukramJ** [comment]
I think this can be closed

**Comment by bcf84** [comment]
The Problem wasn't solved, but okay, let's close this. I'll hang with a recovery snapshot of my vm.
