### ISSUE TITLE
Error log after update to 0.18.0

### ISSUE THREAD

**Issue by emufan** [SukramJ/hahomematic#159]
Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
0.18.0

**Home Assistant version (if applicable):**
2021.12.7

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): CCU3
- OS (Original, RaspberryMatic, debmatic/...): Original
- Version: 3.61.7

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? HMIP

**Describe the bug**

I updated to 0.18.0 and got a lot of errors during restart afterwards.

one time
```
2022-01-11 09:35:31 ERROR (Thread-4) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py", line 567, in run
    self._central.run_coroutine(self._check_connection())
  File "/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py", line 337, in run_coroutine
    return asyncio.run_coroutine_threadsafe(coro, self.loop).result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 443, in result
    raise CancelledError()
concurrent.futures._base.CancelledError
```

severel of
```
2022-01-11 09:35:32 WARNING (Thread-5) [homeassistant.util.executor] Thread[SyncWorker_6] is still running at shutdown: File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 550, in shutdown
    self.join()
  File "/usr/local/lib/python3.9/threading.py", line 1053, in join
    self._wait_for_tstate_lock()
  File "/usr/local/lib/python3.9/threading.py", line 1069, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
```

and one 
```
    2022-01-11 09:35:38 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 550, in shutdown
    self.join()
  File "/usr/local/lib/python3.9/threading.py", line 1053, in join
    self._wait_for_tstate_lock()
  File "/usr/local/lib/python3.9/threading.py", line 1069, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
```

After reboot, the integration was disabled. After another still disabled
```
2022-01-11 09:42:24 ERROR (MainThread) [homeassistant.setup] Setup failed for hahm: Integration not found.
```

After re-downloading in HACS and restart, it was fine again.

I thought, perhaps you take anything out of the logs and behavior. If not, just close or I will close, because as written, after re-download and restart it is fine - at least for now.

**Comment by SukramJ** [comment]
Good that you reported this, but i cannot reproduce it.
