### ISSUE TITLE
I can control my roller shutter only in one direction

### ISSUE THREAD

**Issue by TobseF** [SukramJ/hahomematic#1702]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I can control my roller shutter (`HmIP-FROLL`) with the ⬇-button of the Home Assistant card. It reacts and goes down. But after it is closed, the ⬇-button is still active and the ⬆-button is grayed out. 
So it's not possible to control my roller shutter it with the UP and DOWN controls.
The only workaround I found is to open the control popup and switch to the slider mode. Here it always switches the mode, so it's possible to open it again.

1. The roller shutter is closed, but the ⬆-button is grayed out.
![Screenshot_20240907-234652](https://github.com/user-attachments/assets/00a92ee2-8037-4e54-bd33-d774e77b00a5)

3. Also in the popup, the ⬆ control is disabled.
![Screenshot_20240907-234700](https://github.com/user-attachments/assets/cb311dbb-89cf-41f4-92f9-f118bebbfec5)

4. The  slider-mode shows the wrong state, but allows to open the roller.
![Screenshot_20240907-234656](https://github.com/user-attachments/assets/ca30a1ec-5796-441c-bf49-c551a8b8e2f4)

I recognized the state was not updated ("opened 20 hours ago"). This is also shown in the history, that my close action was executed but not tracked:
![Screenshot_20240907-234958](https://github.com/user-attachments/assets/746d04ba-7052-4b96-b8e5-bb4549b3d77b)

Controlling the roller shutter in the CCU3 Webinterface always works, because both ⬆ and ⬇ buttons are always active.
Is there a way to ignore the last state and always show the buttons as active? For example, the 🟦-stop-button is always active. By pressing it, I can hear the actor executes the stop, even if the roller is not moving. So allowing it to execute an up command, even if it thinks it's already opened, should be possible.

Of course this is only a workaround. But it would solve my problem and should always be an option to control something, regardless of the current (wrong) state.

I can see some problems in the notification section:
<img width="400" alt="2024-09-07_23h49_07" src="https://github.com/user-attachments/assets/f4af2d82-0543-4244-af5d-c8e41edf4cd2">
And I also saw the info in the log:
```txt
1: You are running multiple instances of HA with the same instance name configured for this integration. Re-add one instance! Otherwise this HA instance will not receive update events from your CCU. Possible reason 
2: Something is stuck on the CCU or hasn't been cleaned up. Therefore, try a CCU restart.Possible reason
3: Your setup is misconfigured and HA is not able to receive events from the CCU.
````

I already updated the CCU the latest: `3.77.7` and also the _HmIP-FROLL_ to version `1.10.16`.  I restarted the CUU several times. My PI5 is the only HA installation present in my LAN. The strange thing is, that the events seems to work sometimes (20 hours ago).

As mentioned, it would be nice to get a hint, if can use the widget without the events - simple and stupid.
But of course any help is welcome. And I'm already very thankful for this plugin which brings back my CCU to the 21th century.

### What version of HomematicIP (local) has the issue?

1.65.0

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

CCU3

### What hardware are you running for your system?

Pi5

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
AttributeError: 'NoneType' object has no attribute 'color'
2024-09-07 21:58:09.817 ERROR (MainThread) [homeassistant.components.scene] Error adding entity scene.wohnbereich_nachtlicht for domain scene with platform hue
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/hue/scene.py", line 189, in extra_state_attributes
    "is_dynamic": self.is_dynamic,
                  ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/hue/scene.py", line 133, in is_dynamic
    if self.resource.palette.color and len(self.resource.palette.color) > 1:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'color'
2024-09-07 21:58:09.821 ERROR (MainThread) [homeassistant.components.scene] Error adding entity scene.schlafzimmer_gedimmt for domain scene with platform hue
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/hue/scene.py", line 189, in extra_state_attributes
    "is_dynamic": self.is_dynamic,
                  ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/hue/scene.py", line 133, in is_dynamic
    if self.resource.palette.color and len(self.resource.palette.color) > 1:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'color'
2024-09-07 21:59:06.381 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('homematicip_local', '01J4Z9D5ZNAKXDJRX7VD11D6NS'): 1146063.472337438}
2024-09-07 22:00:06.463 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('homematicip_local', '01J4Z9D5ZNAKXDJRX7VD11D6NS'): 1146063.472337438}
2024-09-07 22:01:06.546 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('homematicip_local', '01J4Z9D5ZNAKXDJRX7VD11D6NS'): 1146063.472337438}
2024-09-07 22:02:06.624 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('homematicip_local', '01J4Z9D5ZNAKXDJRX7VD11D6NS'): 1146063.472337438}
2024-09-07 22:06:41.590 WARNING (MainThread) [hahomematic.caches.dynamic] Pending PONG mismatch: There is a mismatch between send ping events and received pong events for HA instance ccu3-HmIP-RF. Possible reason 1: You are running multiple instances of HA with the same instance name configured for this integration. Re-add one instance! Otherwise this HA instance will not receive update events from your CCU. Possible reason 2: Something is stuck on the CCU or hasn't been cleaned up. Therefore, try a CCU restart.Possible reason 3: Your setup is misconfigured and HA is not able to receive events from the CCU.
2024-09-07 22:06:41.600 WARNING (MainThread) [hahomematic.caches.dynamic] Pending PONG mismatch: There is a mismatch between send ping events and received pong events for HA instance ccu3-BidCos-RF. Possible reason 1: You are running multiple instances of HA with the same instance name configured for this integration. Re-add one instance! Otherwise this HA instance will not receive update events from your CCU. Possible reason 2: Something is stuck on the CCU or hasn't been cleaned up. Therefore, try a CCU restart.Possible reason 3: Your setup is misconfigured and HA is not able to receive events from the CCU.
2024-09-07 22:06:41.605 WARNING (MainThread) [hahomematic.caches.dynamic] Pending PONG mismatch: There is a mismatch between send ping events and received pong events for HA instance ccu3-VirtualDevices. Possible reason 1: You are running multiple instances of HA with the same instance name configured for this integration. Re-add one instance! Otherwise this HA instance will not receive update events from your CCU. Possible reason 2: Something is stuck on the CCU or hasn't been cleaned up. Therefore, try a CCU restart.Possible reason 3: Your setup is misconfigured and HA is not able to receive events from the CCU.
```

**Comment by SukramJ** [comment]
> Home Assistant Container

Please read the [docs](https://github.com/danielperna84/custom_homematic#homematicip-local-documentation) and search for Docker. Your CCU is not able to send events to HA.

**Comment by SukramJ** [comment]
Can this be closed?

**Comment by SukramJ** [comment]
I guess this can be closed.
