### ISSUE TITLE
Reinstallation after deletion not possible due to several problems

### ISSUE THREAD

**Issue by mane1895** [SukramJ/hahomematic#1734]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hello everyone,

I use HomeAssistant (HAOS V13.1, Core V2024.9.3, Supervisor V2024.09.01) on a mini PC, Raspberrymatic (3.77.7.20240826) on a Pi4 and the current Homematic(IP) Local Integration from HACS (V 2.0.1) and have been having major problems for many weeks.

After the reinstallation everything worked perfectly.

Since the first HAOS/Core update, all Raspberrymatic entities are no longer available and cannot be deleted. Activate or deactivate, or every attempt at reconfiguration has failed.

I also have no way of reinstalling the integration.

In order to delete the integration, it was necessary to manually remove all folders. But even now, when Homematic(IP) Local is obviously not installed, it is not possible to perform a new installation.

"500: Internal Server Error Server got itself in trouble" is all that keeps coming up.

I suspect that there is some old code lying around somewhere in the Python scripts that is preventing the new installation.

Every protocol basically ends with this:
"Requirements for homematicip_local not found: ['hahomematic==2024.9.12']"

Does anyone have any idea what I can do? I've had these problems since July and I always hoped that updates would hopefully fix the problem.
But that was never the case.

Best regards, mane

### What version of HomematicIP (local) has the issue?

Current, but actually Not installed 

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.x

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
2024-10-01 13:50:20.353 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-01 13:50:20.354 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration dwains_dashboard which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-01 13:50:20.354 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-01 13:50:20.707 DEBUG (MainThread) [homeassistant.components.hassio.coordinator] Finished fetching hassio data in 0.014 seconds (success: True)
2024-10-01 13:50:30.593 ERROR (MainThread) [custom_components.hacs] Could not update plugin - Error fetching data from HACS: Cannot connect to host data-v2.hacs.xyz:443 ssl:default [Connection reset by peer]
2024-10-01 13:50:30.598 ERROR (MainThread) [custom_components.hacs] Could not update template - Error fetching data from HACS: Cannot connect to host data-v2.hacs.xyz:443 ssl:default [Connection reset by peer]
2024-10-01 13:50:30.598 ERROR (MainThread) [custom_components.hacs] Could not update integration - Error fetching data from HACS: Cannot connect to host data-v2.hacs.xyz:443 ssl:default [Connection reset by peer]
2024-10-01 13:50:30.599 ERROR (MainThread) [custom_components.hacs] Could not update theme - Error fetching data from HACS: Cannot connect to host data-v2.hacs.xyz:443 ssl:default [Connection reset by peer]
2024-10-01 13:50:40.386 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package hahomematic==2024.9.12: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/hahomematic/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/hahomematic/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/hahomematic/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/hahomematic/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/hahomematic/
ERROR: Could not find a version that satisfies the requirement hahomematic==2024.9.12 (from versions: none)
ERROR: No matching distribution found for hahomematic==2024.9.12
2024-10-01 13:50:49.794 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package hahomematic==2024.9.12: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/hahomematic/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/hahomematic/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/hahomematic/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/hahomematic/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/hahomematic/
ERROR: Could not find a version that satisfies the requirement hahomematic==2024.9.12 (from versions: none)
ERROR: No matching distribution found for hahomematic==2024.9.12
2024-10-01 13:50:59.322 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package hahomematic==2024.9.12: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/hahomematic/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/hahomematic/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/hahomematic/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/hahomematic/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/hahomematic/
ERROR: Could not find a version that satisfies the requirement hahomematic==2024.9.12 (from versions: none)
ERROR: No matching distribution found for hahomematic==2024.9.12
2024-10-01 13:50:59.323 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 108, in _async_start
    await gather_with_limited_concurrency(FLOW_INIT_LIMIT, *init_coros)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 114, in gather_with_limited_concurrency
    return await gather(
           ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 112, in sem_task
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1296, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1321, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1462, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2913, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2890, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 575, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 153, in async_get_integration_with_requirements
    return await int_or_fut
           ^^^^^^^^^^^^^^^^
homeassistant.requirements.RequirementsNotFound: Requirements for homematicip_local not found: ['hahomematic==2024.9.12'].
```

**Comment by SukramJ** [comment]
Sorry this is not an issue within this integartion. 
Your HA is not able to establish a connection to download the dependency hahomematic.
Looks like a network problem.

**Comment by mane1895** [comment]
I can also see from the logs that the site is not accessible. But that cannot be the cause of the problem that entities could not be deleted; everything only worked indirectly. Everything worked until the update.

**Comment by SukramJ** [comment]
Deine Beschreibung ist nicht verständlich!
Irgendwas hast Du auf deinem System zerlegt.
Entweder Du spielst ein altes Backup ein, oder Du setzt dein HAOS neu auf.

**Comment by mane1895** [comment]
Ja, das sehe ich sogar ein. Ich habe selbst völlig den Überblick verloren.
Backup einspielen bringt nichts - auch kein Backup, bei dem die Homematic Local Integration noch nicht einmal installiert war.
Neu aufgesetzt habe ich es ebenfalls schon. Es funktioniert bis zum ersten Update…
Keine Updates machen ist natürlich auch keine Lösung.

**Comment by SukramJ** [comment]
> Neu aufgesetzt habe ich es ebenfalls schon. Es funktioniert bis zum ersten Update…

Update von was?

**Comment by mane1895** [comment]
Wenn ich mich recht erinnere, standen ein Core und ein Supervisor Update an. Die habe ich durchgeführt und danach sah ich erstmals auf dem Dashboard, dass meine HM Entitäten nicht verfügbar waren, danach bei der Integration selber „nicht geladen“.

**Comment by SukramJ** [comment]
Wie gesagt, da bin ich raus. 
Deine Logs sehen für mich klar nach Netzwerk Problemen aus.
Versuch es vielleicht mal im HA Community Forum.

**Comment by mane1895** [comment]
Danke trotzdem für deine Zeit und Mühe :)
