### ISSUE TITLE
Error after upgrade to 1.66.0

### ISSUE THREAD

**Issue by hoegertn** [SukramJ/hahomematic#1742]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I am getting the following error in HA after upgrade. Homematic devices are not available in HA at all

### What version of HomematicIP (local) has the issue?

1.66.0 and 1.67.0pre

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
Logger: homeassistant.config_entries
Quelle: config_entries.py:594
Erstmals aufgetreten: 00:23:23 (1 Vorkommnisse)
Zuletzt protokolliert: 00:23:23

Error setting up entry ccu3-webui for homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homematicip_local/__init__.py", line 78, in async_setup_entry
    await control.start_central()
  File "/config/custom_components/homematicip_local/control_unit.py", line 238, in start_central
    await super().start_central()
  File "/config/custom_components/homematicip_local/control_unit.py", line 130, in start_central
    await self._central.start()
  File "/usr/local/lib/python3.12/site-packages/hahomematic/central/__init__.py", line 398, in start
    await self._start_clients()
  File "/usr/local/lib/python3.12/site-packages/hahomematic/central/__init__.py", line 491, in _start_clients
    if await self._create_clients():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hahomematic/central/__init__.py", line 524, in _create_clients
    if client := await hmcl.create_client(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hahomematic/client/__init__.py", line 1237, in create_client
    return await _ClientConfig(central=central, interface_config=interface_config).get_client()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hahomematic/client/__init__.py", line 1153, in get_client
    check_proxy = await self._get_simple_xml_rpc_proxy()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hahomematic/client/__init__.py", line 1202, in _get_simple_xml_rpc_proxy
    return await self.get_xml_rpc_proxy(auth_enabled=True, max_workers=0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hahomematic/client/__init__.py", line 1197, in get_xml_rpc_proxy
    await xml_proxy.do_init()
  File "/usr/local/lib/python3.12/site-packages/hahomematic/client/xml_rpc.py", line 98, in do_init
    if supported_methods := await self.system.listMethods():
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hahomematic/client/xml_rpc.py", line 126, in __async_request
    result = await self._looper.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Global task timeout
```

**Comment by SukramJ** [comment]
> asyncio.exceptions.CancelledError: Global task timeout

Looks like your CCU is not responding. Restart it.

**Comment by hoegertn** [comment]
Thanks that worked. Funny thing was that Homematic was still working and it occurred exactly at the point of update.
