### ISSUE TITLE
Device deletion not working

### ISSUE THREAD

**Issue by eikowagenknecht** [SukramJ/hahomematic#189]
After you posted the howto for deleting devices in response to my last issue, now here's another one because it does not seem to work for me right now.

I removed 3 devices from the CCU3 but they are still in Home Assistant.

What did not work:
- Restart HA
- Restart the Integration
- Activate them, use the hahm_delete_device service, then restart the integration, then restart HA

I'm a bit lost how to get rid of them ;-)

**custom_component/hahomematic version (if applicable):**
latest

**Home Assistant version (if applicable):**
latest

**CCU version:**
CCU3 with Raspberrymatic

**Comment by eikowagenknecht** [comment]
After another reboot I could remove all entities of the device (they were in status "recovered") but the device itself still won't delete.

**Comment by SukramJ** [comment]
Please provide more information as requested in the issue template, esp. logs.

I tested this morning and it works as expected:
- I removed a device in my RM this morning and it gets immediately in HA.
- Afterwards i readded a device to my RM and it appeared in HA.
- I renamed the device in RM
- I removed the device from HA with haha.delete_device, and the device is gone.
- After a reload of the integration the device appeared with the new name and the correct area assignment.

**Comment by eikowagenknecht** [comment]
Interesting that it works for you. Here is more information as requested:

These are the devices I want to delete:
![image](https://user-images.githubusercontent.com/1475672/149657745-9484e1c6-9c77-4996-a225-668a4cae27d9.png)

I renamed them in the CCU before replacing them with other devices and this is reflected in the name (xx***), so it obviously picked up the name change.

Anyways, I set it to debug logging now.

On HA startup I got the following messages (not sure if related):

```
2022-01-16 12:33:50 INFO (MainThread) [hahomematic.client] proxy_init: Proxy for CCU3-HmIP-RF initialized
2022-01-16 12:33:50 DEBUG (MainThread) [hahomematic.client] proxy_init: init('http://192.168.40.32:40969', 'CCU3-BidCos-RF')
2022-01-16 12:33:51 DEBUG (MainThread) [hahomematic.central_unit] CentralUnit.add_new_devices: interface_id = CCU3-HmIP-RF, dev_descriptions = 558
2022-01-16 12:33:52 DEBUG (MainThread) [hahomematic.client] fetch_names_json: Fetching names via JSON-RPC.
2022-01-16 12:33:52 DEBUG (MainThread) [hahomematic.json_rpc_client] json_rpc_client._post: Method: Session.login
2022-01-16 12:33:52 DEBUG (MainThread) [hahomematic.json_rpc_client] json_rpc_client._post: API-Endpoint: http://192.168.40.31/api/homematic.cgi
2022-01-16 12:33:52 DEBUG (MainThread) [hahomematic.json_rpc_client] json_rpc_client._post: Method: Device.listAllDetail
2022-01-16 12:33:52 DEBUG (MainThread) [hahomematic.json_rpc_client] json_rpc_client._post: API-Endpoint: http://192.168.40.31/api/homematic.cgi
2022-01-16 12:33:55 DEBUG (MainThread) [hahomematic.entity]  switch: Failed to get value for HM-Sen-RD-O, QEQ0808396:2, STATE: 

Logger: hahomematic.client
Source: /usr/local/lib/python3.9/site-packages/hahomematic/client.py:254
First occurred: 12:34:10 (1 occurrences)
Last logged: 12:34:10

set_value: ProxyException
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_proxy.py", line 55, in __async_request
    return await self._async_add_proxy_executor_job(
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_proxy.py", line 47, in _async_add_proxy_executor_job
    return await self._loop.run_in_executor(self._proxy_executor, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1458, in __request
    response = self.__transport.request(
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1160, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1176, in single_request
    return self.parse_response(resp)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1348, in parse_response
    return u.close()
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 662, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -1: 'Generic error'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hahomematic/client.py", line 252, in set_value
    await self._proxy.setValue(channel_address, parameter, value)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_proxy.py", line 65, in __async_request
    raise ProxyException(fex) from fex
hahomematic.exceptions.ProxyException: <Fault -1: 'Generic error'>

2022-01-16 12:34:13 DEBUG (MainThread) [hahomematic.json_rpc_client] json_rpc_client._post: Method: Session.logout
2022-01-16 12:34:13 DEBUG (MainThread) [hahomematic.json_rpc_client] json_rpc_client._post: API-Endpoint: http://192.168.40.31/api/homematic.cgi
2022-01-16 12:34:13 DEBUG (MainThread) [hahomematic.client] fetch_names_json: Resolving devicenames
```

Using the "delete_device" service just logs:

```
2022-01-16 12:40:07 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2022-01-16 12:40:07 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2022-01-16 12:40:07 DEBUG (MainThread) [hahomematic.central_unit] CentralUnit.delete_device: interface_id = CCU3-BidCos-RF, device_address = NEQ1575003
```

and doesn't seem to do anything.

What might be interesting is that on startup I see entries like 

```
2022-01-16 12:33:49 DEBUG (MainThread) [hahomematic.device] Device.__init__: Initializing device: CCU3-BidCos-RF, QEQ0808396
2022-01-16 12:33:49 DEBUG (MainThread) [hahomematic.device] Device.__init__: Initialized device: CCU3-BidCos-RF, QEQ0808396, HM-Sen-RD-O, AU.Garten Regensensor (Gerät)
```

for all my devices but not the deleted ones (NEQ1575003 for example).

Are there any other logs / information that I can provide?

**Comment by SukramJ** [comment]
Please retest with latest version

**Comment by eikowagenknecht** [comment]
No change, service still doesn't delete the device. Same logs:

```
2022-01-17 09:12:52 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2022-01-17 09:12:52 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2022-01-17 09:12:52 DEBUG (MainThread) [hahomematic.central_unit] CentralUnit.delete_device: interface_id = CCU3-BidCos-RF, device_address = NEQ1574594
```

**Comment by SukramJ** [comment]
Sprechen wir eigentlich generell darüber, dass das Löschen bei dir nicht funktioniert, oder geht es nur um das Device ohne Entities?
Der Service macht eigentlich nur das Gleich, was durch ein Löschen eines Gerätes in der CCU ausgelöst wird, d.h. es werden die Entiäten aus hahomamatic entfernt, wodurch auch die Entitäten in HA über das Löschen per callback informiert werden. Wenn dein Gerät aber keine Entitäten mehr hat, weil diese manuell gelöscht worden sind, kann der Callback auf HA natürlich nicht mehr greifen, und es bleibt nur die leere Device Hülle in HA, die ansonsten mit gelöscht wird.
Mir ist aktuell kein UI aufrufbarer Service bekannt, der ein Device aus der DeviceRegistry entfernt.
Ich persönlich würde den Eintrag, nach Backup, manuell aus der Datei löschen.

**Comment by eikowagenknecht** [comment]
Das Löschen hat zumindest für diese Geräte (inkl. deren Entities) generell nicht funktioniert, heißt: Gar nichts getan. Jedenfalls wurde in HA weder Gerät noch Entity gelöscht automatisch.

Ggf. hängt es damit zusammen, dass ich die Geräte (inkl. aller Entities) in HA deaktiviert hatte zu dem Zeitpunkt, als ich sie in der CCU gelöscht habe?

Evtl. habe ich die Situation durch das manuelle Löschen der Entities dann verschlimmbessert, das kann sein.

Ich mache mal bei core einen Issue auf, dass man leere Geräte nicht entfernen kann. Das ist ja doch eher unpraktisch, in den internen Dateien von HA herumfummeln zu müssen dafür.

**Comment by SukramJ** [comment]
> Ggf. hängt es damit zusammen, dass ich die Geräte (inkl. aller Entities) in HA deaktiviert hatte zu dem Zeitpunkt, als ich sie in der CCU gelöscht habe?

zu 100%
Deaktivierte Geräte stehen nicht unter der Kontrolle der Integration. 

Hattest Du das schon mal erwähnt?

**Comment by eikowagenknecht** [comment]
Habe ich anscheinend nicht erwähnt, sorry. Ich habe das Gerät mitsamt Entities allerdings nach dem Entfernen aus der CCU dann auch wieder aktiviert als es nicht gelöscht wurde und dann nochmal den Service drauf los gelassen. Auch das hat nichts gebracht.

Es scheint mir generell ein etwas seltsamer Umgang mit deaktivierten Geräten / Entitäten vom Core, wenn diese dann effektiv nicht mehr entfernt werden können.. aber das ist ja ein anderes Thema und hat vermutlich mit der Integration hier nichts zu tun.

Ich hab's nun manuell aus der registry entfernt, nun sind sie weg.
