### ISSUE TITLE
system variables are no longer working with the update to v1.73.0

### ISSUE THREAD

**Issue by walburgf** [SukramJ/hahomematic#1903]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I'm getting the following message after updating to 1.73.0:
"Failed to setup, check the logs"

As a result, all devices are created, but the system variables are no longer "connected"

The detail in the log is:

2024-12-09 10:27:31.529 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  raspberrymatic for homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homematicip_local/__init__.py", line 92, in async_setup_entry
    await control.start_central()
  File "/config/custom_components/homematicip_local/control_unit.py", line 242, in start_central
    await super().start_central()
  File "/config/custom_components/homematicip_local/control_unit.py", line 128, in start_central
    await self._central.start()
  File "/usr/local/lib/python3.13/site-packages/hahomematic/central/__init__.py", line 409, in start
    await self._start_clients()
  File "/usr/local/lib/python3.13/site-packages/hahomematic/central/__init__.py", line 515, in _start_clients
    await self._init_hub()
  File "/usr/local/lib/python3.13/site-packages/hahomematic/central/__init__.py", line 633, in _init_hub
    await self._hub.fetch_sysvar_data(scheduled=True)
  File "/usr/local/lib/python3.13/site-packages/hahomematic/decorators.py", line 46, in service_wrapper
    return_value = await func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hahomematic/model/hub/__init__.py", line 72, in fetch_sysvar_data
    await self._update_sysvar_data_points()
  File "/usr/local/lib/python3.13/site-packages/hahomematic/model/hub/__init__.py", line 127, in _update_sysvar_data_points
    variables = await client.get_all_system_variables(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        include_internal=self._config.include_internal_sysvars
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/hahomematic/decorators.py", line 46, in service_wrapper
    return_value = await func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hahomematic/client/__init__.py", line 1168, in get_all_system_variables
    return await self._json_rpc_client.get_all_system_variables(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        include_internal=include_internal
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/hahomematic/client/json_rpc.py", line 530, in get_all_system_variables
    descriptions = await self._get_system_variable_descriptions()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hahomematic/client/json_rpc.py", line 600, in _get_system_variable_descriptions
    response = await self._post_script(script_name=RegaScript.GET_SYSTEM_VARIABLE_DESCRIPTIONS)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hahomematic/client/json_rpc.py", line 287, in _post_script
    response[_JsonKey.RESULT] = orjson.loads(response[_JsonKey.RESULT])
                                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: unexpected control character in string: line 104 column 72 (char 5515)


### What version of HomematicIP (local) has the issue?

1.73.0

### What was the last working version of HomematicIP (local)?

1.72.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.79.6.20241122

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[2024-12-09 - Error after updating to 1.73.0 v0.txt](https://github.com/user-attachments/files/18059369/2024-12-09.-.Error.after.updating.to.1.73.0.v0.txt)


### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
Log details (ERROR)
Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 10:27:31 AM (2 occurrences)
Last logged: 10:36:50 AM

Error setting up entry raspberrymatic for homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homematicip_local/__init__.py", line 92, in async_setup_entry
    await control.start_central()
  File "/config/custom_components/homematicip_local/control_unit.py", line 242, in start_central
    await super().start_central()
  File "/config/custom_components/homematicip_local/control_unit.py", line 128, in start_central
    await self._central.start()
  File "/usr/local/lib/python3.13/site-packages/hahomematic/central/__init__.py", line 409, in start
    await self._start_clients()
  File "/usr/local/lib/python3.13/site-packages/hahomematic/central/__init__.py", line 515, in _start_clients
    await self._init_hub()
  File "/usr/local/lib/python3.13/site-packages/hahomematic/central/__init__.py", line 633, in _init_hub
    await self._hub.fetch_sysvar_data(scheduled=True)
  File "/usr/local/lib/python3.13/site-packages/hahomematic/decorators.py", line 46, in service_wrapper
    return_value = await func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hahomematic/model/hub/__init__.py", line 72, in fetch_sysvar_data
    await self._update_sysvar_data_points()
  File "/usr/local/lib/python3.13/site-packages/hahomematic/model/hub/__init__.py", line 127, in _update_sysvar_data_points
    variables = await client.get_all_system_variables(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        include_internal=self._config.include_internal_sysvars
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/hahomematic/decorators.py", line 46, in service_wrapper
    return_value = await func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hahomematic/client/__init__.py", line 1168, in get_all_system_variables
    return await self._json_rpc_client.get_all_system_variables(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        include_internal=include_internal
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/hahomematic/client/json_rpc.py", line 530, in get_all_system_variables
    descriptions = await self._get_system_variable_descriptions()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hahomematic/client/json_rpc.py", line 600, in _get_system_variable_descriptions
    response = await self._post_script(script_name=RegaScript.GET_SYSTEM_VARIABLE_DESCRIPTIONS)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hahomematic/client/json_rpc.py", line 287, in _post_script
    response[_JsonKey.RESULT] = orjson.loads(response[_JsonKey.RESULT])
                                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: unexpected control character in string: line 104 column 72 (char 5515)
```


### Additional information

_No response_

**Comment by SukramJ** [comment]
See #1898


Dublicate [See](https://github.com/danielperna84/hahomematic/discussions/1898#discussioncomment-11495856)
Fixed with #1899

**Comment by SukramJ** [comment]
Fehlermeldung in der CCU/RM:

`Bezeichnungen dürfen keines der folgenden Zeichen enthalten: <, >, ', ", &, $, [, ], {, } und \`

**Comment by 21-Jailbraik-21** [comment]
Hi, I have the same problem.
What do I need to change to continue?

I don't know where to look.

Thanks

**Comment by SukramJ** [comment]
Follow the link in my first reply.
