### ISSUE TITLE
ProxyException on startup

### ISSUE THREAD

**Issue by eikowagenknecht** [SukramJ/hahomematic#199]
**custom_component/hahomematic version (if applicable):**
latest

**Home Assistant version (if applicable):**
latest

**CCU version:**
CCU3 with Raspberrymatic
**Problem-relevant configuration:**
Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use? Hm, HmIP

**Describe the bug**
On every startup, the following error is logged:

```
Logger: hahomematic.client
Source: /usr/local/lib/python3.9/site-packages/hahomematic/client.py:254
First occurred: 15:40:15 (1 occurrences)
Last logged: 15:40:15

set_value: ProxyException
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_proxy.py", line 55, in __async_request
    return await self._async_add_proxy_executor_job(
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_proxy.py", line 47, in _async_add_proxy_executor_job
    return await self._loop.run_in_executor(self._proxy_executor, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1458, in __request
    response = self.__transport.request(
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1160, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1176, in single_request
    return self.parse_response(resp)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1348, in parse_response
    return u.close()
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 662, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -1: 'Generic error'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hahomematic/client.py", line 252, in set_value
    await self._proxy.setValue(channel_address, parameter, value)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_proxy.py", line 65, in __async_request
    raise ProxyException(fex) from fex
hahomematic.exceptions.ProxyException: <Fault -1: 'Generic error'>
```

**To Reproduce**
1. Restart HA

**Expected behavior**
No errors on a normal startup.

**Additional context**
Seems to work fine though.

**Comment by eikowagenknecht** [comment]
Also some exceptions on shutdown:

```
2022-01-16 16:02:15 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /homeassistant/restart request
2022-01-16 16:02:15 ERROR (Thread-7) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py", line 598, in run
    self._central.run_coroutine(self._check_connection())
  File "/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py", line 386, in run_coroutine
    return asyncio.run_coroutine_threadsafe(coro, self.loop).result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 443, in result
    raise CancelledError()
concurrent.futures._base.CancelledError
2022-01-16 16:02:25 ERROR (Thread-6) [hahomematic.xml_rpc_server] RPCFunctions.event: Failed to call callback for: CCU3-HmIP-RF, 002D1D898C86AA:1, CONCENTRATION
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_server.py", line 65, in event
    callback(interface_id, channel_address, parameter, value)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 423, in event
    self.update_entity(self.unique_id)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 92, in update_entity
    _callback(*args)
  File "/config/custom_components/hahm/generic_entity.py", line 108, in _async_device_changed
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 629, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1232, in async_set
    self._bus.async_fire(
  File "/usr/src/homeassistant/homeassistant/core.py", line 734, in async_fire
    self._hass.async_add_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 365, in async_add_hass_job
    self.loop.call_soon(hassjob.target, *args)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2022-01-16 16:02:25 ERROR (Thread-6) [hahomematic.xml_rpc_server] RPCFunctions.event: Failed to call callback for: CCU3-HmIP-RF, 002D1D898C86AA:4, ACTUAL_TEMPERATURE
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_server.py", line 65, in event
    callback(interface_id, channel_address, parameter, value)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 423, in event
    self.update_entity(self.unique_id)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 92, in update_entity
    _callback(*args)
  File "/config/custom_components/hahm/generic_entity.py", line 108, in _async_device_changed
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 629, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1232, in async_set
    self._bus.async_fire(
  File "/usr/src/homeassistant/homeassistant/core.py", line 734, in async_fire
    self._hass.async_add_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 365, in async_add_hass_job
    self.loop.call_soon(hassjob.target, *args)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2022-01-16 16:02:25 ERROR (Thread-6) [hahomematic.xml_rpc_server] RPCFunctions.event: Failed to call callback for: CCU3-HmIP-RF, 002D1D898C86AA:4, HUMIDITY
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_server.py", line 65, in event
    callback(interface_id, channel_address, parameter, value)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 423, in event
    self.update_entity(self.unique_id)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 92, in update_entity
    _callback(*args)
  File "/config/custom_components/hahm/generic_entity.py", line 108, in _async_device_changed
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 629, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1232, in async_set
    self._bus.async_fire(
  File "/usr/src/homeassistant/homeassistant/core.py", line 734, in async_fire
    self._hass.async_add_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 365, in async_add_hass_job
    self.loop.call_soon(hassjob.target, *args)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by SukramJ** [comment]
I ignore the shutdown restart/exception for now as they are expected, but should not be displayed.

Startup:
I wonder about the `set_value`. Do you have an automation running that writes data or changes the state of an entity?

**Comment by eikowagenknecht** [comment]
> I wonder about the `set_value`. Do you have an automation running that writes data or changes the state of an entity?

Not that I know of, at least not on system startup. To check, I just restarted and looked at the "last triggered" date of my automations and only one one was running before that error occurred. And that one is definitely not related to homematic (just sending a notification on startup to my phone).

**Comment by SukramJ** [comment]
Ok, next release takes care of exception handling.

**Comment by SukramJ** [comment]
Please retest

**Comment by eikowagenknecht** [comment]
The previous ProxyException is gone. But on this restart I had other exceptions and it took a really long time (~10min?) until my wall switches started to work again.

```
Logger: homeassistant.components.number
Source: custom_components/hahm/generic_entity.py:88
Integration: Nummer (documentation, issues)
First occurred: 09:20:37 (1 occurrences)
Last logged: 09:20:37

Error adding entities for domain number with platform hahm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 747, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/hahm/generic_entity.py", line 88, in async_added_to_hass
    await self._hm_entity.load_data()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 444, in load_data
    self._value = self._convert_value(
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 316, in _convert_value
    return float(value)  # type: ignore[return-value]
ValueError: could not convert string to float: ''
```

```
Logger: hahomematic.client
Source: /usr/local/lib/python3.9/site-packages/hahomematic/client.py:262
First occurred: 09:21:04 (1 occurrences)
Last logged: 09:21:04

set_value failed: ProxyException: 000A1A49A1090A:1, SET_POINT_TEMPERATURE, 22.0
```

```
Logger: hahomematic.client
Source: /usr/local/lib/python3.9/site-packages/hahomematic/client.py:434
First occurred: 09:21:16 (1 occurrences)
Last logged: 09:21:16

fetch_names_json: General exception
```

```
Logger: homeassistant
Source: custom_components/hahm/generic_entity.py:88
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 09:21:17 (1 occurrences)
Last logged: 09:21:17

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 747, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/hahm/generic_entity.py", line 88, in async_added_to_hass
    await self._hm_entity.load_data()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 444, in load_data
    self._value = self._convert_value(
  File "/usr/local/lib/python3.9/site-packages/hahomematic/entity.py", line 316, in _convert_value
    return float(value)  # type: ignore[return-value]
ValueError: could not convert string to float: ''
```

**Comment by danielperna84** [comment]
Your latest exception reminds me of what I have fixed here: https://github.com/home-assistant/core/pull/64208

It seems as sometimes when performing the `getValue` during startup, the device doesn't respond with a valid value. Typically it should be the correct value. But for some reason there are cases where they return `None` or just empty strings.

**Comment by SukramJ** [comment]
I'll catch the `ValueError` and return `None` instead.

**Comment by SukramJ** [comment]
@eikowagenknecht:
Please restest with 0.24.2.
Conversion error should be gone, and the others should show more details.

**Comment by eikowagenknecht** [comment]
Now it's just:

```
Logger: hahomematic.client
Source: /usr/local/lib/python3.9/site-packages/hahomematic/client.py:266
First occurred: 12:16:16 (1 occurrences)
Last logged: 12:16:16

set_value failed with ProxyException ((<Fault -1: 'Generic error'>,)): 000A1A49A10408:1, SET_POINT_TEMPERATURE, 21.5
```

Also a warning, but that might be unrelated:

```
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:484
Integration: Sensor (documentation, issues)
First occurred: 12:20:10 (1 occurrences)
Last logged: 12:20:10

The unit of sensor.sonnenschein_heute (min) does not match the unit of already compiled statistics (#). Generation of long term statistics will be suppressed unless the unit changes back to #
```

**Comment by SukramJ** [comment]
1. What device is 000A1A49A10408? How do you call set_temperature?

2. go to dev tools/statistics and solvethe issue there.

**Comment by eikowagenknecht** [comment]
1. It's an HmIP-eTRV-2.

![image](https://user-images.githubusercontent.com/1475672/149932866-c4fa01de-d766-406b-863a-20fcb993c25c.png)

I do not call set_temperature at bootup. Maybe it's the Scheduler integration that is calling this at bootup, though. Have to check that later.

2. Huh, didn't yet know that menu existed. Thanks!

**Comment by danielperna84** [comment]
FYI  
I just did a fresh test-installation with the latest version (0.25.0), and I don't get any exceptions during startup / shutdown / restart. How is it working for you now @eikowagenknecht ?

**Comment by eikowagenknecht** [comment]
Working fine now after I removed the scheduler integration.
