### ISSUE TITLE
sensor value > 255 characters

### ISSUE THREAD

**Issue by trilu2000** [SukramJ/hahomematic#449]
there is an eufy camera addon available for the raspberrymatic wich generates variables to manage the security camera within the ccu.
the variables are forwarded to Homeassistant via your integration without an issue - but not for the camera picture link, there i receive an error message within the logfile:

`2022-05-17 07:51:24 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/homematicip_local/control_unit.py", line 667, in _async_fetch_data
    await self._hm_hub.fetch_data()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/hub.py", line 230, in fetch_data
    await self._update_entities()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/hub.py", line 275, in _update_entities
    await entity.set_value(value)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/hub.py", line 196, in set_value
    self.update_entity()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/hub.py", line 124, in update_entity
    _callback(self.unique_id)
  File "/config/custom_components/homematicip_local/generic_entity.py", line 114, in _async_device_changed
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 680, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1354, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1040, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.myccu_sv_eufycameraimageurlt8113n1319490f30. State max length is 255 characters.`

the link of the ccu variable looks like:
`https://cdn-eu.eufylife.com/thumb/2022/05/16/station/T8010Nxxxxxxxxxx/9WIed4sgc8atUAQn./camera01_20220516180612.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXXXXXXXXX/20220517/eu-central-1/s3/aws4_request&X-Amz-Date=20220517T075028Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=fe685e224fde6880d8e4b0517bbf6925a8ad78affff2c5692cfc5dcc443fcc25`

Would it be possible to enlarge the sensor status to 512 chars?

**Comment by SukramJ** [comment]
No.
This error is not related to this integration. We don't limit text length.
This is a core limitation.
