### ISSUE TITLE
ImportError: cannot import name 'cleanup_cache_dirs' from 'hahomematic.central_unit'

### ISSUE THREAD

**Issue by emufan** [SukramJ/hahomematic#463]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.5.4

**Home Assistant version (if applicable):**
2022.5.5

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): CCU3
- OS (Original, RaspberryMatic, debmatic/...): Original
- Version: 3.63.9

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? HMIP, Bidcos, Groups

**Describe the bug**
Today I build a new test machine and now I'm getting an error after each reboot

**Relevant HA log entries (full log)**
```
2022-05-27 19:34:02 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration homematicip_local: cannot import name 'cleanup_cache_dirs' from 'hahomematic.central_unit' (/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py)
2022-05-27 19:34:02 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 743, in async_create_flow
integration.get_platform("config_flow")
File "/usr/src/homeassistant/homeassistant/loader.py", line 603, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 620, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/config/custom_components/homematicip_local/__init__.py", line 6, in <module>
from hahomematic.central_unit import cleanup_cache_dirs
ImportError: cannot import name 'cleanup_cache_dirs' from 'hahomematic.central_unit' (/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
await gather_with_concurrency(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 192, in gather_with_concurrency
return await gather(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 190, in sem_task
return await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 223, in _async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 750, in async_create_flow
raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
```

**Comment by SukramJ** [comment]
Please describe your test machine.
Looks like the hahomematic dependency is missing in your setup.

**Comment by emufan** [comment]
Clean docker image on QNAP NAS. Clean new installation of integration. Integration is working.

**Comment by SukramJ** [comment]
I cannot reproduce this on my `venv` and `HAOS` enviroments. I don't use a container installation.
`cleanup_cache_dirs` is included in `hahomematic.central_unit` for a long time.

If you know how, please check the content of `/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py` in HA container.

**Comment by emufan** [comment]
I'll do next days.

**Comment by emufan** [comment]
Yes. It is included in this file.

```
def cleanup_cache_dirs(instance_name: str, storage_folder: str) -> None:
    """Clean up the used cached directories."""
    cache_dir = f"{storage_folder}/cache"
    files_to_delete = [FILE_DEVICES, FILE_PARAMSETS]

    def _delete_file(file_name: str) -> None:
        if os.path.exists(os.path.join(cache_dir, file_name)):
            os.unlink(os.path.join(cache_dir, file_name))

    for file_to_delete in files_to_delete:
        _delete_file(file_name=f"{instance_name}_{file_to_delete}")
```

**Comment by SukramJ** [comment]
I installed HA 2022.5.5 in docker on an ubuntu 22.04 and followed the docs from HA, without any annoying logs.
So i still cannot reproduce this.

**Comment by emufan** [comment]
Started all over again. And now the errors didn't show up anymore till now. Komich.

**Comment by emufan** [comment]
Ich werde wiedereröffnen, falls es nochmal/wieder erscheint
