### ISSUE TITLE
Not working any more after 1.8.3 update

### ISSUE THREAD

**Issue by eikowagenknecht** [SukramJ/hahomematic#486]
**custom_component/hahomematic version (if applicable):**
1.8.3

**Home Assistant version (if applicable):**
2022.6.0

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes 
Which interfaces do you use? hm, hmip

**Describe the bug**

Devices don't work any more on 1.8.3. No keypress events etc.

**Relevant HA log entries (full log)**
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/homematicip_local/control_unit.py:111 
Integration: Homematic(IP) Local (documentation, issues) 
First occurred: 23:40:21 (1 occurrences) 
Last logged: 23:40:21

Error setting up entry CCU3 for homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/homematicip_local/__init__.py", line 29, in async_setup_entry
    await control.async_start()
  File "/config/custom_components/homematicip_local/control_unit.py", line 111, in async_start
    await self._central.start()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py", line 231, in start
    await self._start_clients()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py", line 270, in _start_clients
    await self._init_hub()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py", line 416, in _init_hub
    await self._hub.fetch_data()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/hub.py", line 96, in fetch_data
    await self._update_entities()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/hub.py", line 114, in _update_entities
    variables = await self._central.get_all_system_variables()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py", line 715, in get_all_system_variables
    return await client.get_all_system_variables()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/client.py", line 710, in get_all_system_variables
    return await self._json_rpc_client.get_all_system_variables()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/json_rpc_client.py", line 422, in get_all_system_variables
    response = await self._post_script(
  File "/usr/local/lib/python3.9/site-packages/hahomematic/json_rpc_client.py", line 235, in _post_script
    response[ATTR_RESULT] = json.loads(response[ATTR_RESULT])
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 118 (char 716)

```

**Comment by SukramJ** [comment]
Please execute this [script](https://github.com/danielperna84/hahomematic/blob/1.8.3/hahomematic/rega_scripts/get_all_system_variables.fn)  and post the result here.

**Comment by SukramJ** [comment]
… execute in CCU.

**Comment by eikowagenknecht** [comment]
```
[{"id": "40","name": "Alarmmeldungen","type": "NUMBER","unit": "","value": "0","description": "Anzahl Alarmmeldungen","isLogged": "false","isVisible": "false","isInternal": "true","channelId": "65535","minValue": "0","maxValue": "65000","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "1236","name": "Alarmzone-1","type": "ALARM","unit": "","value": "","description": "Alarmmeldung Alarmzone 1","isLogged": "false","isVisible": "true","isInternal": "false","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "nicht ausgelöst","valueName1": "ausgelöst"},
{"id": "950","name": "CcuImReboot","type": "LOGIC","unit": "","value": "false","description": "Umgewidmete Variable "Anwesenheit"","isLogged": "false","isVisible": "true","isInternal": "false","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "Normalbetrieb","valueName1": "Startvorgang"},
{"id": "18221","name": "DutyCycle","type": "NUMBER","unit": "%","value": "16.000000","description": "DutyCycle CCU","isLogged": "false","isVisible": "true","isInternal": "false","channelId": "65535","minValue": "-1","maxValue": "100","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "26212","name": "DutyCycle-Alarm","type": "ALARM","unit": "","value": "","description": "DutyCycle 99% (PEQ1096369)","isLogged": "true","isVisible": "true","isInternal": "false","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "nicht ausgelöst","valueName1": "ausgelöst"},
{"id": "33381","name": "LetzterReboot","type": "STRING","unit": "","value": "30.05.2022 14:25:34","description": "Datum des letzten Starts der CCU (für Home Assistant)","isLogged": "false","isVisible": "true","isInternal": "false","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "34095","name": "Lueftung-Bad","type": "LOGIC","unit": "","value": "false","description": "Zielwert für den Lüfter","isLogged": "false","isVisible": "true","isInternal": "false","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "aus","valueName1": "an"},
{"id": "25158","name": "Lueftung-BueroSchlafzimmer-Ist","type": "NUMBER","unit": "Stufe","value": "0.000000","description": "Aktueller Wert des Lüfters","isLogged": "false","isVisible": "true","isInternal": "false","channelId": "65535","minValue": "0","maxValue": "5","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "25159","name": "Lueftung-BueroSchlafzimmer-Soll","type": "NUMBER","unit": "Stufe","value": "0.000000","description": "Zielwert für den Lüfter","isLogged": "false","isVisible": "true","isInternal": "false","channelId": "65535","minValue": "0","maxValue": "5","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "24771","name": "Lueftung-KuecheWohnzimmer-Ist","type": "NUMBER","unit": "Stufe","value": "0.000000","description": "Aktueller Wert des Lüfters","isLogged": "false","isVisible": "true","isInternal": "false","channelId": "65535","minValue": "0","maxValue": "5","valueList": "","valueName0": "5","valueName1": "0"},
{"id": "24770","name": "Lueftung-KuecheWohnzimmer-Soll","type": "NUMBER","unit": "Stufe","value": "0.000000","description": "Zielwert für den Lüfter","isLogged": "false","isVisible": "true","isInternal": "false","channelId": "65535","minValue": "0","maxValue": "5","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "37275","name": "NachrichtAdmin","type": "STRING","unit": "","value": "0.0","description": "Nachricht über Home Assistant an Admin senden","isLogged": "false","isVisible": "true","isInternal": "false","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "37276","name": "NachrichtAnwesende","type": "STRING","unit": "","value": "0.0","description": "Nachricht über Home Assistant an anwesende Personen senden","isLogged": "false","isVisible": "true","isInternal": "false","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "2922","name": "pcCCUID","type": "STRING","unit": "","value": "PC_B5675B60-9F67-4407-B0D5-54D682A5AAA7","description": "","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "2924","name": "pocketControlPushMessage","type": "STRING","unit": "","value": "CCU wurde neu gestartet!","description": "Change the value to push. Do not delete!","isLogged": "false","isVisible": "true","isInternal": "false","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "2923","name": "pushCCUID","type": "STRING","unit": "","value": "P_CB2276A4-3272-4152-8084-F2676C6380F5","description": "","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "41","name": "Servicemeldungen","type": "NUMBER","unit": "","value": "12","description": "Anzahl Servicemeldungen","isLogged": "false","isVisible": "false","isInternal": "true","channelId": "65535","minValue": "0","maxValue": "65000","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "17884","name": "svEnergyCounter_17868_0001D3C99C8C56:6","type": "NUMBER","unit": "","value": "395.700000","description": "","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "0","maxValue": "1.7e+308","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "18291","name": "svEnergyCounter_18275_0001D3C99C8BF3:6","type": "NUMBER","unit": "","value": "386060.900000","description": "","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "0","maxValue": "1.7e+308","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "17885","name": "svEnergyCounterOldVal_17868","type": "NUMBER","unit": "","value": "0.100000","description": "","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "0","maxValue": "1.7e+308","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "18292","name": "svEnergyCounterOldVal_18275","type": "NUMBER","unit": "","value": "3883.600000","description": "","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "0","maxValue": "1.7e+308","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "20120","name": "svHmIPRainCounter_20075_00185A498C4401:1","type": "NUMBER","unit": "","value": "121.500000","description": "","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "0","maxValue": "1.7e+308","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "20118","name": "svHmIPRainCounterOldVal_20075","type": "NUMBER","unit": "","value": "121.500000","description": "","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "0","maxValue": "1.7e+308","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "20119","name": "svHmIPRainCounterToday_20075","type": "NUMBER","unit": "","value": "0.000000","description": "","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "20075","minValue": "0","maxValue": "1.7e+308","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "20121","name": "svHmIPRainCounterYesterday_20075","type": "NUMBER","unit": "","value": "0.000000","description": "","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "20075","minValue": "0","maxValue": "1.7e+308","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "20103","name": "svHmIPSunshineCounter_20075_00185A498C4401:1","type": "NUMBER","unit": "","value": "50782.000000","description": "","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "0","maxValue": "1.7e+308","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "20104","name": "svHmIPSunshineCounterOldVal_20075","type": "NUMBER","unit": "","value": "1633.000000","description": "","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "0","maxValue": "1.7e+308","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "20105","name": "svHmIPSunshineCounterToday_20075","type": "NUMBER","unit": "","value": "106.000000","description": "","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "20075","minValue": "0","maxValue": "1.7e+308","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "20106","name": "svHmIPSunshineCounterYesterday_20075","type": "NUMBER","unit": "","value": "700.000000","description": "","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "20075","minValue": "0","maxValue": "1.7e+308","valueList": "","valueName0": "0","valueName1": "1"},
{"id": "18688","name": "WatchDog-Alarm","type": "ALARM","unit": "","value": "","description": "No internet connection detected","isLogged": "true","isVisible": "true","isInternal": "false","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "nicht ausgelöst","valueName1": "ausgelöst"},
{"id": "33076","name": "WatchDog: chronyd-restart","type": "ALARM","unit": "","value": "","description": "Chrony-NTP restarted","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "nicht ausgelöst","valueName1": "ausgelöst"},
{"id": "33082","name": "WatchDog: dutycycle-","type": "ALARM","unit": "","value": "","description": "DutyCycle 99% (98A99A22B1)","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "nicht ausgelöst","valueName1": "ausgelöst"},
{"id": "36742","name": "WatchDog: eq3configd-restart","type": "ALARM","unit": "","value": "","description": "eq3configd restarted","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "nicht ausgelöst","valueName1": "ausgelöst"},
{"id": "33413","name": "WatchDog: hmipserver-restart","type": "ALARM","unit": "","value": "","description": "HMIPServer restarted","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "nicht ausgelöst","valueName1": "ausgelöst"},
{"id": "36748","name": "WatchDog: lighttpd-restart","type": "ALARM","unit": "","value": "","description": "lighttpd restarted","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "nicht ausgelöst","valueName1": "ausgelöst"},
{"id": "33378","name": "WatchDog: no-internet","type": "ALARM","unit": "","value": "","description": "No internet connection detected","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "nicht ausgelöst","valueName1": "ausgelöst"},
{"id": "33585","name": "WatchDog: regahss-restart","type": "ALARM","unit": "","value": "","description": "ReGaHss restarted","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "nicht ausgelöst","valueName1": "ausgelöst"},
{"id": "36751","name": "WatchDog: rfd-restart","type": "ALARM","unit": "","value": "","description": "rfd restarted","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "nicht ausgelöst","valueName1": "ausgelöst"},
{"id": "36745","name": "WatchDog: ssdpd-restart","type": "ALARM","unit": "","value": "","description": "ssdpd restarted","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "nicht ausgelöst","valueName1": "ausgelöst"},
{"id": "33410","name": "WatchDog: unclean-shutdown","type": "ALARM","unit": "","value": "","description": "Unclean shutdown or system crash identified","isLogged": "false","isVisible": "true","isInternal": "true","channelId": "65535","minValue": "","maxValue": "","valueList": "","valueName0": "nicht ausgelöst","valueName1": "ausgelöst"}]
```

**Comment by Baxxy13** [comment]
Ungünstige `" "` in der Beschreibung der originalen SysVar Anwesenheit würde ich auf die Schnelle sagen.

**Comment by SukramJ** [comment]
Das sollte mit der 1.8.4 behoben sein

**Comment by eikowagenknecht** [comment]
Danke, nun geht es wieder :-)

**Comment by Baxxy13** [comment]
Bisschen OT: Das verlinkte Script zieht ja auch Informationen die m.E. in HA unnötig sind. 
.DPArchive() und .Channel() sehe ich als solche an.
.Visible() eventuell auch noch. 

Würde ich zwecks Ressourcen - Schonung gleich weglassen wenn du da nichts von nutzt.

**Comment by SukramJ** [comment]
Aktuell [suche](https://github.com/danielperna84/hahomematic/blob/devel/hahomematic/rega_scripts/get_system_variables_ext_marker.fn) ich nur noch nach dem Marker.
Die Sysvar hole ich mir wieder über Sysvar.getall, um mir das "escapen" zu ersparen.
