### ISSUE TITLE
Unable to prepare setup for platform homematicip_local.climate: Platform not found (Exception importing custom_components.homematicip_local.climate).

### ISSUE THREAD

**Issue by norgur** [SukramJ/hahomematic#534]
Hey,
I just updated the integration via HACS and am now unable to start it.
Log:
Logger: homeassistant.loader
Source: custom_components/homematicip_local/entity_helpers.py:56
Integration: Homematic(IP) Local ([documentation](https://github.com/danielperna84/custom_homematic), [issues](https://github.com/danielperna84/hahomematic/issues))
First occurred: 11:07:10 (11 occurrences)
Last logged: 11:07:10

    Unexpected exception importing platform custom_components.homematicip_local.climate
    Unexpected exception importing platform custom_components.homematicip_local.select
    Unexpected exception importing platform custom_components.homematicip_local.switch
    Unexpected exception importing platform custom_components.homematicip_local.siren
    Unexpected exception importing platform custom_components.homematicip_local.light

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/binary_sensor.py", line 18, in <module>
    from .generic_entity import HaHomematicGenericEntity, HaHomematicGenericSysvarEntity
  File "/config/custom_components/homematicip_local/generic_entity.py", line 22, in <module>
    from .entity_helpers import get_entity_description
  File "/config/custom_components/homematicip_local/entity_helpers.py", line 56, in <module>
    "FREQUENCY": HmNumberEntityDescription(
TypeError: __init__() got an unexpected keyword argument 'native_unit_of_measurement'

**Comment by SukramJ** [comment]
Please fill  out the issue template.

**Comment by norgur** [comment]
Oh, sorry I didn't see the template. My bad!
Thanks for your quick reply,
I managed solved the issue by reinstalling python.
