### ISSUE TITLE
Integration fails to load after update 1.18.0

### ISSUE THREAD

**Issue by ND1988** [SukramJ/hahomematic#640]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
1.8.0

**known last working custom_component version (if applicable):**
1.7.0

**Home Assistant version (if applicable):**
2022.9.7

**CCU version:**
- Raspi3
- RaspberryMatic: 3.65.8.20220831

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use (hmip/bidcos/wired)? Hmip 

**Describe the bug**
After update the integration fails to load

**To Reproduce**
Restart of HA and/or reload of integration

**Screenshots (if applicable)**
- CCU firewall
- integrations view
- device view
- enity view

**Relevant HA log entries (full log)**
```

Logger: homeassistant.config_entries
Source: helpers/entity.py:526 
First occurred: 19:23:48 (1 occurrences) 
Last logged: 19:23:48

Error setting up entry RaspberryMatic for homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/homematicip_local/__init__.py", line 57, in async_setup_entry
    await control.async_start()
  File "/config/custom_components/homematicip_local/control_unit.py", line 122, in async_start
    await self._central.start()
  File "/usr/local/lib/python3.10/site-packages/hahomematic/central_unit.py", line 196, in start
    await self._start_clients()
  File "/usr/local/lib/python3.10/site-packages/hahomematic/central_unit.py", line 241, in _start_clients
    await self._init_hub()
  File "/usr/local/lib/python3.10/site-packages/hahomematic/central_unit.py", line 379, in _init_hub
    await self._hub.fetch_sysvar_data()
  File "/usr/local/lib/python3.10/site-packages/hahomematic/hub.py", line 87, in fetch_sysvar_data
    await self._update_hub_state()
  File "/usr/local/lib/python3.10/site-packages/hahomematic/hub.py", line 104, in _update_hub_state
    self.update_entity()
  File "/usr/local/lib/python3.10/site-packages/hahomematic/entity.py", line 112, in update_entity
    _callback(*args)
  File "/config/custom_components/homematicip_local/control_unit.py", line 798, in _async_update_hub
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity RaspberryMatic>

```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**
Working integration 😊

**Additional context**
—-

**Comment by SukramJ** [comment]
What happens after a restart?
Do you have an entity `sensor.{your_instance_name})`? sensor.raspberrymatic ?
Is the entity sensor.{your_instance_name}) enabled?

**Comment by ND1988** [comment]
The same happens after a restart

![6E34C56D-E855-418B-9B81-1DC7FBB248D4](https://user-images.githubusercontent.com/81183688/193647026-92d8f8cd-b626-440c-af21-b82bdc8e553d.png)
![78E16EE9-34F2-4FF1-B36D-D025D2CD857C](https://user-images.githubusercontent.com/81183688/193647032-fadc68d7-29a1-46b2-a55e-52029bb971b8.png)

**Comment by SukramJ** [comment]
Please retest with with 1.18.1

**Comment by ND1988** [comment]
Error is gone!
Thx for the very fast support😊
