### ISSUE TITLE
ConfigFlow broken?

### ISSUE THREAD

**Issue by SukramJ** [SukramJ/hahomematic#82]
### Discussed in https://github.com/danielperna84/hahomematic/discussions/80

<div type='discussions-op-text'>

<sup>Originally posted by **itn3rd77** December 22, 2021</sup>
Hi,

in der aktuellsten Version 0.1.2 kann ich den ConfigFlow nicht mehr erfolgreich abschließen. Mit der Fehlemdlung aus dem Log kann ich leider nicht genau erkennen wo der Fehler liegt.

![grafik](https://user-images.githubusercontent.com/2655169/147070582-0da00d7c-8209-4932-b5f1-06c9db15634d.png)

```
2021-12-22 10:29:51 WARNING (MainThread) [custom_components.hahm.config_flow] ConfigFlow.step_interface, no user input
2021-12-22 10:29:53 ERROR (MainThread) [custom_components.hahm.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/hahm/config_flow.py", line 210, in async_step_interface
    await _async_validate_input(self.hass, self.data)
  File "/config/custom_components/hahm/config_flow.py", line 126, in _async_validate_input
    control_unit = ControlConfig(
  File "/config/custom_components/hahm/control_unit.py", line 392, in get_control_unit
    return ControlUnit(self)
  File "/config/custom_components/hahm/control_unit.py", line 87, in __init__
    self._central: CentralUnit = self.create_central()
  File "/config/custom_components/hahm/control_unit.py", line 319, in create_central
    xml_rpc_server = register_xml_rpc_server(
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_server.py", line 338, in register_xml_rpc_server
    xml_rpc = XMLRPCServer(local_ip, local_port)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_server.py", line 259, in __init__
    self.local_port: int = int(local_port)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```</div>

**Comment by SukramJ** [comment]
Fixed in  0.2.0
