### ISSUE TITLE
Can't turn off HM-LC-Dim1L-CV

### ISSUE THREAD

**Issue by noxhirsch** [SukramJ/hahomematic#94]
After moving my setup, I noticed that I'm not able to turn off my HM-LC-Dim1L-CV anymore - while turning it on or setting it to specific levels works fine. To make sure that it's not a problem with the device I set up the old integration again - there it turns off as it should.
In the log I get this error while switching it off:

```
2021-12-26 00:40:01 ERROR (MainThread) [hahomematic.client] set_value: ProxyException
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_proxy.py", line 62, in __async_request
    return await self._async_add_proxy_executor_job(
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_proxy.py", line 54, in _async_add_proxy_executor_job
    return await self._loop.run_in_executor(self._proxy_executor, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1458, in __request
    response = self.__transport.request(
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1160, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1176, in single_request
    return self.parse_response(resp)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1348, in parse_response
    return u.close()
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 662, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -1: 'Failure'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hahomematic/client.py", line 246, in set_value
    await self._proxy.setValue(channel_address, parameter, value)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_proxy.py", line 72, in __async_request
    raise ProxyException(fex) from fex
hahomematic.xml_rpc_proxy.ProxyException: <Fault -1: 'Failure'>
```

I don't know what else might be needed to find the problem - if you could tell me I'll do my best to provide this info.

**Comment by SukramJ** [comment]
Hi, please check of you can turn off the dimmer with a Service.
Go to development tools , Services.
Select hahm.set_device_value. 
Choose your device. 
Select Channel 1
Parameter is LEVEL
Please try value with 0 and 0.0 (with a dot)
Optional set the value_type to double.

Please tell me if one combination works.

**Comment by noxhirsch** [comment]
When I do that, I get a new error in the log and the dimmer state does not change (I tried all combinations):

```
2021-12-26 01:27:15 ERROR (MainThread) [hahomematic.client] set_value: ProxyException
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_proxy.py", line 62, in __async_request
    return await self._async_add_proxy_executor_job(
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_proxy.py", line 54, in _async_add_proxy_executor_job
    return await self._loop.run_in_executor(self._proxy_executor, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1458, in __request
    response = self.__transport.request(
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1160, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1176, in single_request
    return self.parse_response(resp)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1348, in parse_response
    return u.close()
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 662, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -2: 'Invalid device'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hahomematic/client.py", line 246, in set_value
    await self._proxy.setValue(channel_address, parameter, value)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/xml_rpc_proxy.py", line 72, in __async_request
    raise ProxyException(fex) from fex
hahomematic.xml_rpc_proxy.ProxyException: <Fault -2: 'Invalid device'>
```

**Comment by SukramJ** [comment]
Hmmh, i believed in the combination of 0.0 and value_type double.
Please send a Screenshot of the service‘s page.

**Comment by noxhirsch** [comment]
Here's one screenshot from UI mode and one from YAML mode: 
![image](https://user-images.githubusercontent.com/30938717/147396257-580a00e8-5bb0-4e0b-a207-68fcb20e0e9f.png)

![image](https://user-images.githubusercontent.com/30938717/147396260-35719c3b-a9a6-4b83-bc65-0319acdea914.png)

**Comment by SukramJ** [comment]
Looks good. I will add something with the next Release.
I hoped to verify it with the Service  before.

**Comment by SukramJ** [comment]
Please test with the latest release.

**Comment by noxhirsch** [comment]
Now it works fine! Thank you for the fast fix!

**Comment by SukramJ** [comment]
Thanks for testing and fast Feedback.
