### ISSUE TITLE
unzählige ERROR-Meldungen auf der Zentrale im hmserver.log seit 1.32.0 

### ISSUE THREAD

**Issue by Baxxy13** [SukramJ/hahomematic#981]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Seit Version 1.32.0 wird das `hmserver.log` auf der Zentrale mit ERROR-Meldungen geflutet.

Ich sehe das hier auf meinem Testsystem und auch auf dem Hauptsystem. 
Auf dem Hauptsystem fiel das bisher nicht so auf da das Logrotate die hmserver.log laufend wegrotiert.
Das Testsystem wird auf einen Syslogserver geloggt, da ist das Logfile in etwa 3 Tagen auf 300MB angewachsen.  

### What version of HomematicIP (local) has the issue?

1.32.0 und höher

### What was the last working version of HomematicIP (local)?

1.31.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.67.10.20230225

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [x] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-0ce79fb3b0f08cd71e037e2ad7b79b82.json (2).txt](https://github.com/danielperna84/hahomematic/files/10883345/config_entry-homematicip_local-0ce79fb3b0f08cd71e037e2ad7b79b82.json.2.txt)

### Anything in the logs that might be useful for us?

```txt
2023-03-03 16:15:48,289 io.vertx.core.impl.ContextImpl ERROR [vert.x-worker-thread-14] Unhandled exception 
java.lang.IllegalArgumentException: Can not set [Ljava.lang.String; field de.eq3.cbcs.legacy.bidcos.rpc.objects.DeviceDescription.children to java.lang.String
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:1.8.0_362]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:1.8.0_362]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[?:1.8.0_362]
	at java.lang.reflect.Field.set(Field.java:764) ~[?:1.8.0_362]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcField.setValue(RpcField.java:69) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseObject(XmlRpcParser.java:447) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseValue(XmlRpcParser.java:392) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseArray(XmlRpcParser.java:519) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseValue(XmlRpcParser.java:385) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:163) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
	at com.sun.proxy.$Proxy42.listDevices(Unknown Source) ~[?:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand.updateDevicesForClient(BackendUpdateDevicesCommand.java:34) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand.run(BackendUpdateDevicesCommand.java:29) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker.handle(BackendWorker.java:27) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker.handle(BackendWorker.java:11) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
2023-03-03 16:15:58,330 io.vertx.core.impl.ContextImpl ERROR [RM-Live-OVA-26-HmIP-RF_WorkerPool-1] Unhandled exception 
de.eq3.cbcs.legacy.communication.rpc.RpcRemoteException: Error requesting method event: <class 'TypeError'>:CentralUnit.fire_entity_event_callback() got an unexpected keyword argument 'parameter' Code: 1
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:155) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
	at com.sun.proxy.$Proxy41.event(Unknown Source) ~[?:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.event(LegacyBackendClient.java:123) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleReceivedStatusData(LegacyBackendNotificationHandler.java:302) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleBackendNotification(LegacyBackendNotificationHandler.java:162) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:106) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:39) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
2023-03-03 16:15:58,339 io.vertx.core.impl.ContextImpl ERROR [vert.x-worker-thread-15] Unhandled exception 
de.eq3.cbcs.legacy.communication.rpc.RpcRemoteException: Error requesting method event: <class 'TypeError'>:CentralUnit.fire_entity_event_callback() got an unexpected keyword argument 'parameter' Code: 1
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:155) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
	at com.sun.proxy.$Proxy42.event(Unknown Source) ~[?:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.vertx.RegaClientWorker.handleEvent(RegaClientWorker.java:73) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.vertx.RegaClientWorker.access$000(RegaClientWorker.java:13) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.vertx.RegaClientWorker$1.handle(RegaClientWorker.java:35) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.vertx.RegaClientWorker$1.handle(RegaClientWorker.java:26) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
2023-03-03 16:16:14,443 io.vertx.core.impl.ContextImpl ERROR [RM-Live-OVA-26-HmIP-RF_WorkerPool-1] Unhandled exception 
de.eq3.cbcs.legacy.communication.rpc.RpcRemoteException: Error requesting method event: <class 'TypeError'>:CentralUnit.fire_entity_event_callback() got an unexpected keyword argument 'parameter' Code: 1
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:155) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
	at com.sun.proxy.$Proxy41.event(Unknown Source) ~[?:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.event(LegacyBackendClient.java:123) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleReceivedStatusData(LegacyBackendNotificationHandler.java:302) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleBackendNotification(LegacyBackendNotificationHandler.java:162) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:106) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:39) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
2023-03-03 16:16:14,451 io.vertx.core.impl.ContextImpl ERROR [vert.x-worker-thread-16] Unhandled exception 
de.eq3.cbcs.legacy.communication.rpc.RpcRemoteException: Error requesting method event: <class 'TypeError'>:CentralUnit.fire_entity_event_callback() got an unexpected keyword argument 'parameter' Code: 1
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:155) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
	at com.sun.proxy.$Proxy42.event(Unknown Source) ~[?:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.vertx.RegaClientWorker.handleEvent(RegaClientWorker.java:73) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.vertx.RegaClientWorker.access$000(RegaClientWorker.java:13) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.vertx.RegaClientWorker$1.handle(RegaClientWorker.java:35) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.vertx.RegaClientWorker$1.handle(RegaClientWorker.java:26) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
```

### Additional information

Mit 1.31.0 sieht das `hmserver.log` nach einem frischen Start der RM und anschließendem Start des HA samt Integration so aus:
(der ERROR kommt einmalig beim Start der Integration)

```
2023-03-03 16:01:58,837 io.vertx.core.impl.ContextImpl ERROR [vert.x-worker-thread-0] Unhandled exception 
java.lang.IllegalArgumentException: Can not set [Ljava.lang.String; field de.eq3.cbcs.legacy.bidcos.rpc.objects.DeviceDescription.children to java.lang.String
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:1.8.0_362]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:1.8.0_362]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[?:1.8.0_362]
	at java.lang.reflect.Field.set(Field.java:764) ~[?:1.8.0_362]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcField.setValue(RpcField.java:69) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseObject(XmlRpcParser.java:447) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseValue(XmlRpcParser.java:392) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseArray(XmlRpcParser.java:519) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseValue(XmlRpcParser.java:385) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:163) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
	at com.sun.proxy.$Proxy42.listDevices(Unknown Source) ~[?:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand.updateDevicesForClient(BackendUpdateDevicesCommand.java:34) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand.run(BackendUpdateDevicesCommand.java:29) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker.handle(BackendWorker.java:27) ~[HMIPServer.jar:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker.handle(BackendWorker.java:11) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
```

**Comment by SukramJ** [comment]
Sehr gut.

**Comment by SukramJ** [comment]
Schau dir doch mal die 1.33.1 an.

**Comment by Baxxy13** [comment]
Sieht bisher sehr gut aus. 
Ich halte mal ein Auge drauf.

**Comment by JoMass** [comment]
danke Baxxy13 dass Du das Thema aufgegriffen und einer Lösung zugeführt hast, danke natürlich vor allem dehnen die eine Lösung gefunden haben.  Das Verhalten ist mit der neuesten Version auch bei mir nun verschwunden !
